// GENERATED by scripts/extract-core.mjs - do not edit by hand.
// Source: ../../../../legacy/cores.js

import { readNumber, clamp } from "./util.js";

// 아크 그리드 — 혼돈 코어와 젬, 그리고 목장/도감/물약처럼 단일 출처인 항목들.
//
// 코어는 해/달/별 각 1개만 장착한다. 포인트 구간(10/14/17/18/19/20)은 누적이라
// 17P를 고르면 10P와 14P 효과도 함께 붙는다. 18~20P는 1포인트마다 같은 값이
// 한 번씩 더 붙는 구간이라 별도로 다룬다.
//
// 17P 줄에 값이 둘(예: 1.0/1.5%)인 것은 코어 단계 차이다. 계산기에서는
// `단계 1 / 단계 2`로 고르게 한다.
//
// 딜 기대값에 반영하지 않는 효과는 아예 싣지 않는다 — 받는 피해 감소, 낙인력,
// 아군 공격력/피해량 강화, 아이덴티티, 방어력, 생명력, 무력화, 최대 마나,
// 화상·부위파괴 같은 별도 피해원.
//
// 평면 공격력/무기 공격력은 이제 셀 수 있다(사전 세팅의 공격력 기준값). 다만
// 별 코어 10P의 실제 수치를 아직 못 구해 그 자리만 비어 있다.

const CHAOS_CORE_POINTS = [10, 14, 17, 18, 19, 20];

const CHAOS_CORE_SLOTS = [
  { key: "sun", label: "해" },
  { key: "moon", label: "달" },
  { key: "star", label: "별" },
];

// 질서 코어. 슬롯은 혼돈과 같이 해·달·별 셋이다.
//
// 효과는 싣지 않는다 — 질서 코어는 직업 전용이라 서른 직업의 표를 따로 들어야
// 하고, 그 표가 없는 채로 목록을 지어내면 계산기가 없는 게임을 계산한다.
// 그래서 이름은 고르는 것이 아니라 적는 것으로 둔다. 캐릭터를 불러오면 게임이
// 준 이름이 그대로 들어온다.
//
// 그러면 왜 두는가. 예전에는 여섯 슬롯 중 질서 셋을 조용히 버리고 '빠졌습니다'
// 한 줄만 남겼다. 무엇을 끼고 있었는지가 화면에 없으니, 계산에 안 들어간다는
// 사실조차 확인할 수가 없었다.
const ORDER_CORE_SLOTS = [
  { key: "sun", label: "해" },
  { key: "moon", label: "달" },
  { key: "star", label: "별" },
];

/** 아무것도 안 낀 질서 세 자리. */
function emptyOrderCores() {
  const out = {};
  ORDER_CORE_SLOTS.forEach(slot => {
    out[slot.key] = { name: "", points: 20, stage: 1 };
  });
  return out;
}

// 코어 등급. 예전에는 '단계 1 / 단계 2'라고 불렀는데 게임의 낱말은 유물·고대다.
// 17P 줄에 값이 둘인 것이 이 차이다 — 안정적인 공격 17P는 유물 1.4%, 고대 2.8%.
const CHAOS_CORE_STAGES = [
  { value: 0, label: "유물" },
  { value: 1, label: "고대" },
];

const CHAOS_CORES = [
  // ── 해 ────────────────────────────────────────────────────────────
  core("sun-brilliant", "sun", "현란한 공격", {
    10: [{ kind: "critOnlyDamage", amount: 0.55 }],
    14: [{ kind: "damage", key: "주는 피해", amount: 0.5 }],
    17: [
      { kind: "damage", key: "주는 피해", amounts: [1.0, 1.5] },
      { kind: "critOnlyDamage", amounts: [0.55, 1.1] },
    ],
    per: [{ kind: "damage", key: "주는 피해", amount: 0.16 }],
  }),
  core("sun-stable", "sun", "안정적인 공격", {
    14: [{ kind: "damage", key: "추가 피해", amount: 0.7 }],
    17: [{ kind: "damage", key: "추가 피해", amounts: [1.4, 2.8] }],
    per: [{ kind: "damage", key: "추가 피해", amount: 0.23 }],
  }, "10P·17P의 받는 피해 감소는 미반영"),
  core("sun-swift", "sun", "재빠른 공격", {
    10: [{ kind: "percent", key: "attackSpeedOnly", amount: 1.0 }],
    14: [{ kind: "percent", key: "critDamage", amount: 1.4 }],
    17: [
      { kind: "percent", key: "attackSpeedOnly", amounts: [2.0, 3.0] },
      { kind: "percent", key: "critDamage", amounts: [2.8, 5.6] },
    ],
    per: [{ kind: "percent", key: "critDamage", amount: 0.45 }],
  }),
  core("sun-faith", "sun", "신념의 강화", {}, "아이덴티티·아군 피해량 강화 전용, 딜 기대값 미반영"),
  core("sun-mana", "sun", "흐르는 마나", {
    14: [{ kind: "percent", key: "skillCooldownReduction", amount: 0.4 }],
    17: [{ kind: "percent", key: "skillCooldownReduction", amounts: [0.8, 1.6] }],
    per: [{ kind: "percent", key: "skillCooldownReduction", amount: 0.13 }],
  }, "최대 마나는 미반영. 쿨감은 최훈/타지 그룹"),
  core("sun-resolve", "sun", "불굴의 강화", {}, "아군 공격력 강화·기상기 쿨감 전용, 딜 기대값 미반영"),

  // ── 달 ────────────────────────────────────────────────────────────
  core("moon-burn", "moon", "불타는 일격", {
    14: [{ kind: "damage", key: "주는 피해", amount: 0.5 }],
    17: [{ kind: "damage", key: "주는 피해", amounts: [1.0, 2.0] }],
    per: [{ kind: "damage", key: "주는 피해", amount: 0.16 }],
  }, "화상 피해는 별도 피해원이라 미반영"),
  core("moon-drain", "moon", "흡수의 일격", {
    14: [{ kind: "damage", key: "주는 피해", amount: 0.5 }],
    17: [{ kind: "damage", key: "주는 피해", amounts: [1.0, 2.0] }],
    per: [{ kind: "damage", key: "주는 피해", amount: 0.16 }],
  }, "생명력 회복은 미반영"),
  core("moon-break", "moon", "부수는 일격", {
    14: [{ kind: "percent", key: "critRate", amount: 0.65 }],
    17: [{ kind: "percent", key: "critRate", amounts: [1.3, 2.6] }],
    per: [{ kind: "percent", key: "critRate", amount: 0.21 }],
  }, "부위 파괴는 미반영"),
  core("moon-brand", "moon", "낙인의 흔적", {}, "낙인력 전용, 딜 기대값 미반영"),
  core("moon-steel", "moon", "강철의 흔적", {}, "방어력 전용, 딜 기대값 미반영"),
  core("moon-lethal", "moon", "치명적인 흔적", {}, "무력화·파티 치피 전용, 딜 기대값 미반영"),

  // ── 별 ────────────────────────────────────────────────────────────
  // 평면 두 줄은 툴팁에 이렇게 온다:
  //   [10P] 공격력이 900 증가한다.
  //   [17P] 공격력이 1.10% 증가하고, 추가로 1800 증가한다.
  // 17P의 평면이 퍼센트 줄에 붙어 있어서 오래 못 보고 지나쳤다. 둘을 넣으니
  // 게임 공격력 194,227을 오차 0.0004%로 재현한다.
  core("star-attack", "star", "공격", {
    10: [{ kind: "flat", key: "attackPower", amount: 900 }],
    14: [{ kind: "damage", key: "공격력", amount: 0.55 }],
    17: [
      { kind: "damage", key: "공격력", amounts: [1.1, 1.65] },
      { kind: "flat", key: "attackPower", amount: 1800 },
    ],
    per: [{ kind: "damage", key: "공격력", amount: 0.16 }],
  }),
  core("star-weapon", "star", "무기", {
    14: [{ kind: "damage", key: "무기 공격력", amount: 0.75 }],
    17: [{ kind: "damage", key: "무기 공격력", amounts: [1.5, 2.25] }],
    per: [{ kind: "damage", key: "무기 공격력", amount: 0.23 }],
  }, "10P의 평면 무기 공격력은 수치 미확보로 미반영 — 직접 입력 효과에 숫자로 적을 수 있습니다"),
  core("star-salvation", "star", "구원", {}, "아군 회복·보호막 전용, 딜 기대값 미반영"),
  core("star-life", "star", "생명", {}, "체력·생명력 전용, 딜 기대값 미반영"),
  core("star-speed", "star", "속도", {
    10: [{ kind: "percent", key: "attackSpeedOnly", amount: 0.9 }],
    14: [{ kind: "percent", key: "moveSpeedOnly", amount: 0.9 }],
    17: [
      { kind: "percent", key: "attackSpeedOnly", amounts: [1.8, 2.7] },
      { kind: "percent", key: "moveSpeedOnly", amounts: [1.8, 2.7] },
    ],
    per: [
      { kind: "percent", key: "attackSpeedOnly", amount: 0.3 },
      { kind: "percent", key: "moveSpeedOnly", amount: 0.3 },
    ],
  }),
  core("star-defense", "star", "방어", {}, "방어력 전용, 딜 기대값 미반영"),
];

function core(id, slot, name, tiers, note = "") {
  const { per = [], ...thresholds } = tiers;
  return { id, slot, name, thresholds, perPoint: per, note, modeled: Object.keys(thresholds).length > 0 };
}

// 아크 그리드 젬. 효과마다 레벨 합계가 따로 있고, 레벨에서 퍼센트로 가는 길은
// **정수 내림 계단**이다. 예전에는 0.0807%/Lv 같은 선형 근사를 썼는데, 그러면
// Lv13에서 1.0491%가 나온다 — 게임은 1.05%다.
//
//   값(%) = floor(레벨 × 계수) / 100
//
// 세 계수 모두 실제 응답과 맞춰 확인했다:
//   공격력 Lv30 → 1.10%,  추가 피해 Lv13 → 1.05%,  보스 피해 Lv10 → 0.83%
const ARK_GRID_GEM_EFFECTS = [
  { key: "attack", label: "공격력", group: "공격력", factor: 3.667 },
  { key: "additional", label: "추가 피해", group: "추가 피해", factor: 8.0834 },
  { key: "boss", label: "보스 피해", group: "보스 피해", factor: 8.3334 },
];

function arkGridGemDamage(key, level) {
  const effect = ARK_GRID_GEM_EFFECTS.find(item => item.key === key);
  if (!effect) return 0;
  const value = clamp(Math.round(readNumber(level)), 0, GEM_MAX_LEVEL);
  return Math.floor(value * effect.factor) / 100;
}

// 레벨 합계다. 실제 응답에서 공격력 30을 봤다.
const GEM_MAX_LEVEL = 60;

// 단일 출처 항목. 켜고 끄거나 수치만 넣으면 되는 것들.
const STANDALONE_SOURCES = {
  ranchCollection: { label: "목장 도감", summary: "추가 피해 +1%", amount: 1 },

};

// 무기 품질 0~100 → 무기 추가 피해 %. y = 0.002x² + 10
// 품질 0에서도 10%이고 100에서 30%다.
const WEAPON_QUALITY_MAX = 100;

function weaponQualityDamage(quality) {
  const q = Math.min(WEAPON_QUALITY_MAX, Math.max(0, Number(quality) || 0));
  return 0.002 * q * q + 10;
}

export {
  CHAOS_CORE_POINTS,
  CHAOS_CORE_SLOTS,
  CHAOS_CORE_STAGES,
  CHAOS_CORES,
  ORDER_CORE_SLOTS,
  emptyOrderCores,
  ARK_GRID_GEM_EFFECTS,
  arkGridGemDamage,
  GEM_MAX_LEVEL,
  STANDALONE_SOURCES,
  WEAPON_QUALITY_MAX,
  weaponQualityDamage,
};
