// GENERATED by scripts/extract-core.mjs - do not edit by hand.
// Source: ../../../../legacy/engravings.js

import { readNumber } from "./util.js";

/**
 * 각인 단계 아홉.
 *
 * 게임이 알려 주는 표는 세 점뿐이다 — 영웅(기본) · 전설 4단계 · 유물 4단계.
 * 그 사이는 4등분이다. 원한이면 전설4 18%에서 유물4 21%까지 0.75%씩:
 *
 *   유물 1단계 18.75 · 2단계 19.5 · 3단계 20.25 · 4단계 21
 *
 * 실측으로 확인했다 — 원한 유물 3단계에 어빌리티 스톤 Lv.2(+3.75%)를 얹으면
 * 게임이 적어 주는 24.00%가 정확히 나온다.
 *
 * from·to는 세 점 표의 첨자다. 영웅은 제자리, 전설은 0→1, 유물은 1→2를 걷는다.
 */
const ENGRAVING_TIERS = [
  { value: "hero", label: "영웅", from: 0, to: 0, step: 0 },
  { value: "legendary1", label: "전설 1단계", from: 0, to: 1, step: 1 },
  { value: "legendary2", label: "전설 2단계", from: 0, to: 1, step: 2 },
  { value: "legendary3", label: "전설 3단계", from: 0, to: 1, step: 3 },
  { value: "legendary4", label: "전설 4단계", from: 0, to: 1, step: 4 },
  { value: "relic1", label: "유물 1단계", from: 1, to: 2, step: 1 },
  { value: "relic2", label: "유물 2단계", from: 1, to: 2, step: 2 },
  { value: "relic3", label: "유물 3단계", from: 1, to: 2, step: 3 },
  { value: "relic4", label: "유물 4단계", from: 1, to: 2, step: 4 },
];

// 옛 저장본의 낱말. "기본"이 영웅이었다.
const LEGACY_ENGRAVING_TIERS = { base: "hero" };

/** 세 점 표에서 단계 하나의 값을 꺼낸다. 사이는 4등분. */
function engravingAmount(amounts, tierIndex) {
  const tier = ENGRAVING_TIERS[tierIndex];
  if (!tier || !Array.isArray(amounts)) return 0;
  const from = readNumber(amounts[tier.from]);
  const to = readNumber(amounts[tier.to]);
  return from + (to - from) * tier.step / 4;
}

/**
 * 어빌리티 스톤이 각인에 얹는 몫.
 *
 * 돌은 각인마다 Lv.1~4를 준다(칸 6/7/9/10개). 단계 사다리와 **따로** 더해진다 —
 * API의 Description은 둘이 이미 합쳐진 값이라, 그걸 단계 표에 억지로 맞추면
 * 원한이 유물 4단계로 잘못 읽힌다.
 *
 * 중첩형(아드레날린·승부사·에테르 포식자)은 표가 중첩당 값을 적어 주므로
 * 최대 중첩을 곱한다. 승부사만 유물에서 중첩이 8 → 12로 는다.
 */
const ENGRAVING_STONE = {
  "master-brawler": { kind: "damage", key: "주는 피해", amounts: [2.7, 3.4, 4.7, 5.4] },
  "ambush-master": { kind: "damage", key: "주는 피해", amounts: [2.7, 3.4, 4.7, 5.4] },
  "masters-tenacity": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "raid-captain": { kind: "special", key: "raidCaptainRate", amounts: [7.5, 9.4, 13.2, 15] },
  "mp-efficiency-increase": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6], manaOnly: true },
  barricade: { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "broken-bone": { kind: "damage", key: "무력화 대상 피해", amounts: [4, 5, 7, 8] },
  "all-out-attack": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "super-charge": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "sight-focus": { kind: "damage", key: "주는 피해", amounts: [4, 5, 7, 8] },
  adrenaline: { kind: "damage", key: "공격력", amounts: [0.48, 0.6, 0.83, 0.95], stacks: [6, 6, 6] },
  "stabilized-status": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "ether-predator": { kind: "damage", key: "공격력", amounts: [0.1, 0.13, 0.18, 0.2], stacks: [30, 30, 30] },
  "keen-blunt-weapon": { kind: "percent", key: "critDamage", amounts: [7.5, 9.4, 13.2, 15] },
  grudge: { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "cursed-doll": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "spirit-absorption": { kind: "percent", key: "attackSpeed", amounts: [3, 3.75, 5.25, 6] },
  "precise-dagger": { kind: "percent", key: "critRate", amounts: [3, 3.75, 5.25, 6] },
  "mass-increase": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  propulsion: { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
  "hit-master": { kind: "damage", key: "주는 피해", amounts: [3, 3.75, 5.25, 6] },
};

/** 돌이 얹는 몫. 레벨은 1~4, 0이면 안 낀 것이다. */
function engravingStoneAmount(id, stoneLevel, tierIndex) {
  const stone = ENGRAVING_STONE[id];
  const level = Math.round(readNumber(stoneLevel));
  if (!stone || level < 1 || level > 4) return null;
  const tier = ENGRAVING_TIERS[tierIndex];
  const stacks = stone.stacks ? readNumber(stone.stacks[tier?.to ?? 0]) : 1;
  return { kind: stone.kind, key: stone.key, manaOnly: stone.manaOnly, amount: readNumber(stone.amounts[level - 1]) * stacks };
}

const ENGRAVING_LIBRARY = [
  engraving("awakening", "각성", "utility", [
    "각성기 쿨감 44% · 횟수 +1",
    "각성기 쿨감 44% · 횟수 +5",
    "각성기 쿨감 50% · 횟수 +5",
  ]),
  engraving("necromancy", "강령술", "utility", [
    "자폭병 · 재사용 21초",
    "자폭병 · 재사용 17초",
    "자폭병 · 재사용 13초",
  ]),
  engraving("fortified-shield", "강화 방패", "utility", [
    "상태이상 면역 · 실드 -64%",
    "상태이상 면역 · 실드 -56%",
    "상태이상 면역 · 실드 -48%",
  ]),
  engraving("master-brawler", "결투의 대가", "damage", [
    "헤드 기준 피해 +16%",
    "헤드 기준 피해 +19.8%",
    "헤드 기준 피해 +22.6%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [16, 19.8, 22.6] },
  ], "headAttack"),
  engraving("drops-of-ether", "구슬동자", "utility", [
    "에테르 · 재사용 16초",
    "에테르 · 재사용 10초",
    "에테르 · 재사용 10초 · 효과 +16%",
  ]),
  engraving("strong-will", "굳은 의지", "utility", [
    "피격 이상 중 받는 피해 -24%",
    "피격 이상 중 받는 피해 -28%",
    "피격 이상 중 받는 피해 -32%",
  ]),
  engraving("vital-point-hit", "급소 타격", "utility", [
    "무력화 +27%",
    "무력화 +32%",
    "무력화 +37%",
  ]),
  engraving("ambush-master", "기습의 대가", "damage", [
    "백어택 기준 피해 +16%",
    "백어택 기준 피해 +19.8%",
    "백어택 기준 피해 +22.6%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [16, 19.8, 22.6] },
  ], "backAttack"),
  engraving("emergency-rescue", "긴급 구조", "utility", [
    "생명력 30% 미만 실드 · 재사용 240초",
    "생명력 30% 미만 실드 · 재사용 200초",
    "생명력 30% 미만 실드 · 재사용 160초",
  ]),
  engraving("masters-tenacity", "달인의 저력", "damage", [
    "주는 피해 +11%",
    "주는 피해 +14%",
    "주는 피해 +17%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [11, 14, 17] },
  ]),
  engraving("raid-captain", "돌격대장", "damage", [
    "이속 증가량의 32%를 피해로 전환",
    "이속 증가량의 40%를 피해로 전환",
    "이속 증가량의 48%를 피해로 전환",
  ], [
    { kind: "special", key: "raidCaptainRate", amounts: [32, 40, 48] },
  ]),
  engraving("magick-stream", "마나의 흐름", "utility", [
    "최대 중첩 쿨감 4%",
    "최대 중첩 쿨감 7%",
    "최대 중첩 쿨감 10%",
  ], [
    { kind: "percent", key: "cooldownReduction", amounts: [4, 7, 10] },
  ]),
  engraving("mp-efficiency-increase", "마나 효율 증가", "damage", [
    "마나 스킬 피해 +11%",
    "마나 스킬 피해 +13%",
    "마나 스킬 피해 +16%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [11, 13, 16], manaOnly: true },
  ]),
  engraving("barricade", "바리케이드", "damage", [
    "실드 중 피해 +11%",
    "실드 중 피해 +14%",
    "실드 중 피해 +17%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [11, 14, 17] },
  ]),
  engraving("lightning-fury", "번개의 분노", "utility", [
    "번개 구체 확률 40%",
    "번개 구체 확률 60%",
    "번개 구체 확률 60% · 시드 추가 피해 140%",
  ]),
  // 대난투에서만 걸린다. 무력화 그룹으로 보내면 대난투 딜 비중이 알아서 섞는다.
  engraving("broken-bone", "부러진 뼈", "damage", [
    "무력화 대상 피해 +32%",
    "무력화 대상 피해 +37%",
    "무력화 대상 피해 +42%",
  ], [
    { kind: "damage", key: "무력화 대상 피해", amounts: [32, 37, 42] },
  ]),
  engraving("fortitude", "불굴", "utility", [
    "받는 피해 최대 -24%",
    "받는 피해 최대 -28%",
    "받는 피해 최대 -32%",
  ]),
  engraving("all-out-attack", "속전속결", "damage", [
    "홀딩·캐스팅 피해 +16%",
    "홀딩·캐스팅 피해 +18%",
    "홀딩·캐스팅 피해 +21%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [16, 18, 21] },
  ]),
  engraving("super-charge", "슈퍼 차지", "damage", [
    "차지 스킬 피해 +16%",
    "차지 스킬 피해 +18%",
    "차지 스킬 피해 +21%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [16, 18, 21] },
  ]),
  engraving("sight-focus", "시선 집중", "damage", [
    "다음 공격 스킬 피해 +20%",
    "다음 공격 스킬 피해 +25%",
    "다음 공격 스킬 피해 +30%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [20, 25, 30] },
  ]),
  engraving("adrenaline", "아드레날린", "damage", [
    "공격력 +5.4% · 치적 +8%",
    "공격력 +5.4% · 치적 +14%",
    "공격력 +5.4% · 치적 +20%",
  ], [
    { kind: "damage", key: "공격력", amounts: [5.4, 5.4, 5.4] },
    { kind: "percent", key: "critRate", amounts: [8, 14, 20] },
  ]),
  engraving("stabilized-status", "안정된 상태", "damage", [
    "주는 피해 +11%",
    "주는 피해 +14%",
    "주는 피해 +17%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [11, 14, 17] },
  ]),
  engraving("divine-protection", "여신의 가호", "utility", [
    "확률 22% · 받는 피해 -38%",
    "확률 22% · 받는 피해 -46%",
    "확률 30% · 받는 피해 -46%",
  ]),
  engraving("ether-predator", "에테르 포식자", "damage", [
    "최대 중첩 공격력 +12.6%",
    "최대 중첩 공격력 +12.6%",
    "최대 중첩 공격력 +16.2%",
  ], [
    { kind: "damage", key: "공격력", amounts: [12.6, 12.6, 16.2] },
  ]),
  engraving("keen-blunt-weapon", "예리한 둔기", "damage", [
    "치피 +36% · 10% 확률로 피해 -20% · 기대값 0.98배",
    "치피 +44% · 10% 확률로 피해 -20% · 기대값 0.98배",
    "치피 +52% · 10% 확률로 피해 -20% · 기대값 0.98배",
  ], [
    { kind: "percent", key: "critDamage", amounts: [36, 44, 52] },
    { kind: "damage", key: "예리한 둔기 패널티", amounts: [-2, -2, -2] },
  ]),
  engraving("grudge", "원한", "damage", [
    "보스에게 주는 피해 +15%",
    "보스에게 주는 피해 +18%",
    "보스에게 주는 피해 +21%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [15, 18, 21] },
  ]),
  engraving("crisis-evasion", "위기 모면", "utility", [
    "사망 피해 무효 · 재사용 640초",
    "사망 피해 무효 · 재사용 560초",
    "사망 피해 무효 · 재사용 480초",
  ]),
  engraving("cursed-doll", "저주받은 인형", "damage", [
    "주는 피해 +11%",
    "주는 피해 +14%",
    "주는 피해 +17%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [11, 14, 17] },
  ]),
  engraving("expert", "전문의", "utility", [
    "실드·회복 +20% · 저체력 추가 +8%",
    "실드·회복 +24% · 저체력 추가 +8%",
    "실드·회복 +28% · 저체력 추가 +8%",
  ]),
  engraving("spirit-absorption", "정기 흡수", "utility", [
    "공격·이동속도 +10%",
    "공격·이동속도 +13%",
    "공격·이동속도 +16%",
  ], [
    { kind: "percent", key: "attackSpeed", amounts: [10, 13, 16] },
  ]),
  engraving("precise-dagger", "정밀 단도", "damage", [
    "치적 +15% · 치피 -6%",
    "치적 +18% · 치피 -6%",
    "치적 +21% · 치피 -6%",
  ], [
    { kind: "percent", key: "critRate", amounts: [15, 18, 21] },
    { kind: "percent", key: "critDamage", amounts: [-6, -6, -6] },
  ]),
  engraving("heavy-armor", "중갑 착용", "utility", [
    "모든 방어력 +74%",
    "모든 방어력 +90%",
    "모든 방어력 +106%",
  ]),
  engraving("mass-increase", "질량 증가", "damage", [
    "주는 피해 +13% · 공격속도 -10%",
    "주는 피해 +16% · 공격속도 -10%",
    "주는 피해 +19% · 공격속도 -10%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [13, 16, 19] },
    { kind: "percent", key: "attackSpeedOnly", amounts: [-10, -10, -10] },
  ]),
  engraving("max-mp-increase", "최대 마나 증가", "utility", [
    "최대 마나 +24%",
    "최대 마나 +28%",
    "최대 마나 +32%",
  ]),
  engraving("propulsion", "추진력", "damage", [
    "스킬 피해 +11%",
    "스킬 피해 +14%",
    "스킬 피해 +17%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [11, 14, 17] },
  ]),
  engraving("hit-master", "타격의 대가", "damage", [
    "비방향성 공격 피해 +11%",
    "비방향성 공격 피해 +14%",
    "비방향성 공격 피해 +17%",
  ], [
    { kind: "damage", key: "주는 피해", amounts: [11, 14, 17] },
  ], "nonDirectional"),
  engraving("master-of-escape", "탈출의 명수", "utility", [
    "기상기 쿨감 19%",
    "기상기 쿨감 23%",
    "기상기 쿨감 27%",
  ]),
  engraving("explosive-expert", "폭발물 전문가", "damage", [
    "배틀아이템 피해 +80% · 소지 +1",
    "배틀아이템 피해 +80% · 소지 +5",
    "배틀아이템 피해 +80% · 소지 +5 · 미소모 20%",
  ]),
];

function engraving(id, name, section, tierSummaries, effects = [], condition = null) {
  return { id, name, section, tierSummaries, effects, condition };
}

// 레이드 내내 유지되지 않는 조건에 묶인 각인 다섯 — 선수필승 · 승부사 ·
// 분쇄의 주먹 · 실드 관통 · 약자 무시 — 은 목록에서 통째로 뺐습니다.
// 예전에는 '기본 제외'로 두고 되돌릴 수 있게 했는데, 딜러 기대값 비교에서
// 되돌릴 이유가 없는 것들이라 고를 수 있다는 사실 자체가 잡음이었습니다.

export {
  ENGRAVING_TIERS,
  LEGACY_ENGRAVING_TIERS,
  engravingAmount,
  ENGRAVING_STONE,
  engravingStoneAmount,
  ENGRAVING_LIBRARY,
};
