// GENERATED by scripts/extract-core.mjs - do not edit by hand.
// Source: ../../../../legacy/app.js (damage model)

import { ARC_PASSIVE_CONSTANTS, ACCESSORY_OPTION_VALUES, EVOLUTION_TIERS, NODE_LIBRARY } from "./data.js";
import { BRACELET_GRADES, BRACELET_STAT_FIELDS, BRACELET_EFFECTS } from "./bracelets.js";
import {
  ENGRAVING_TIERS, ENGRAVING_LIBRARY, engravingAmount, engravingStoneAmount, LEGACY_ENGRAVING_TIERS,
} from "./engravings.js";
import {
  CHAOS_CORE_POINTS, CHAOS_CORE_SLOTS, CHAOS_CORE_STAGES, CHAOS_CORES, emptyOrderCores,
  ARK_GRID_GEM_EFFECTS, arkGridGemDamage, GEM_MAX_LEVEL, STANDALONE_SOURCES,
  WEAPON_QUALITY_MAX, weaponQualityDamage,
} from "./cores.js";
import { awakeningBonuses } from "./awakening.js";
import {
  SYNERGY_SLOTS, getSynergyJob, normalizeSynergyRows, normalizeUptimeMap, synergyBonuses,
} from "./synergy.js";
import { readNumber, clamp, cloneState, makeId } from "./util.js";

const DEFAULT_STATE = {
  // 전투 특성은 출처별로 받는다 — 악세서리 / 팔찌 / 도감·물약.
  // base.*Stat은 모델의 합산 시작점일 뿐이라 0에서 출발한다.
  base: {
    critStat: 0,
    specStat: 0,
    swiftStat: 0,
    // 카드 · 도감 · 물약을 완성한 기준값. 제압은 대난투에서 피해가 되므로
    // 0으로 두면 대난투 비중을 적어도 아무 값이 안 나온다.
    dominationStat: 79,
    enduranceStat: 0,
    expertiseStat: 0,
    specDamagePer100: 0,
  },
  settings: {
    // 진화 포인트는 140 고정이다.
    pointBudget: 140,
    backAttack: false,
    headAttack: false,
  },
  convenience: {
    petStat: "none",
    // 서포터가 얹어 주는 공격력. 기본 공격력을 안 적으면 내 것을 쓴다 —
    // 레이드는 대개 비슷한 스펙끼리 간다.
    support: { on: false, baseAttackPower: 0, skillLevel: 14, attackBoostPercent: 40 },
    evolutionKarmaRank: 0,
    // 옛 단일 슬라이더. damageMix가 채워지면 더 읽지 않는다.
    manaShare: 100,
    damageMix: null,
    // 대난투 딜 비중(%). 무력화 대상 피해는 이 비중만큼만 실린다.
    staggerShare: 0,
    // 레이드에 들어가면 거의 항상 받는 것들이라 켜 둔 채로 시작한다.
    goddessBlessing: true,
    feast: true,
    // 서포터의 아크 그리드가 딜러에게 주는 진화형 피해. 1Lv 6%, 2Lv 12%.
    // 파티가 깔아 주는 것이라 파티 시너지 칸에 산다. 레이드에서는 거의 항상
    // 2렙이 깔리므로 그것을 기본값으로 둔다.
    passionDance: 2,
    // 사람이 직접 고른 적이 있는가. 기본값이 바뀐 뒤에도 고른 값을 지키려면
    // "안 골랐음"과 "0을 골랐음"을 갈라야 한다.
    passionDanceSet: false,
    // 음식 하나. 탐색 갈래이기도 하다 — FOODS 참고.
    food: "none",
    // 깨달음의 카르마 레벨. 1레벨당 무기 공격력 +0.1%. API에 안 실려 온다.
    awakeningKarmaLevel: 0,
  },
  accessories: {
    necklace: { additionalDamage: "none", dealtDamage: "none" },
    earrings: [
      { attackPower: "none", weaponAttack: "none" },
      { attackPower: "none", weaponAttack: "none" },
    ],
    rings: [
      { critRate: "none", critDamage: "none" },
      { critRate: "none", critDamage: "none" },
    ],
  },
  // 평면 증가를 퍼센트로 환산하는 기준값. 팔찌 무공 +9,000이 몇 %인지는
  // 지금 무공이 얼마인지를 알아야 정해진다 — 그래서 여기가 비어 있는 동안은
  // 평면 항목을 통째로 버려 왔다.
  //
  //   기본 공격력 = √(힘민지 × 무기 공격력 / 6)
  //
  // 셋 다 0이면 예전과 똑같이 굴러간다. 평면 항목만 계속 버려질 뿐이다.
  attack: {
    // 손으로 적는 최종값. 아래 조각이 채워지면 그쪽이 이긴다.
    weaponAttack: 0,
    mainStat: 0,
    flatAttack: 0,
    // 불러오기가 채우는 조각들 — assembleAttack 참고.
    weaponFlat: 0,
    weaponPercent: 0,
    mainFlat: 0,
    // 게임의 기본 공격력에서 되짚은 힘민지 총합. 있으면 이쪽이 이긴다.
    mainTotal: 0,
    // 되짚기 재료 — 게임이 알려 준 기본 공격력 D와 그 위에 곱해진 보석·스톤 %,
    // 그리고 팔찌까지 포함한 무공 평면. assembleAttack이 이걸로 힘민지를 푼다.
    baseAttackPower: 0,
    baseScalePercent: 0,
    // 장비가 평면으로 주는 기본 공격력. 완갑이 +850을 준다.
    //
    // 배수와 만나는 순서가 중요하다 — 순수 공격력에 **먼저 더한 뒤** 배수를
    // 먹는다. 실측: 지능 696,294 · 무공 243,319이면 C = 168,041이고,
    // (168,041 + 850) x 1.081 = 182,571로 게임의 182,568과 3 차이다.
    // 나중에 더하면 182,503으로 65가 어긋난다.
    baseFlat: 0,
    weaponFlatAll: 0,
    // 아바타는 부위별 등급으로 든다. 퍼센트 한 칸이었을 때는 "8%"만 남아서
    // 어느 부위가 비었는지, 영웅을 전설로 갈면 얼마가 오르는지 알 수 없었다.
    avatars: { weapon: "none", head: "none", top: "none", bottom: "none" },
  },
  bracelet: {
    stats: { critStat: 0, specStat: 0, swiftStat: 0 },
    // 힘민지는 등급이 아니라 범위다 — 고대 기준 9,600~16,000 사이의 아무 값.
    // 그래서 값을 그대로 든다.
    mainStat: 0,
    effects: {},
  },
  arkGrid: {
    // 질서 코어. 이름만 적어 두고 딜에는 안 싣는다 — legacy/cores.js 참고.
    order: emptyOrderCores(),
    cores: {
      sun: { id: "none", points: 20, stage: 1 },
      moon: { id: "none", points: 20, stage: 1 },
      star: { id: "none", points: 20, stage: 1 },
    },
    // 젬은 효과마다 레벨 합계가 따로다. 예전에는 추가 피해 하나만 들었다.
    gems: { attack: 0, additional: 0, boss: 0 },
  },
  collection: {
    // 펫 목장은 둘이다. 추가 피해를 주는 목장과 힘민지를 주는 목장이 따로 있고
    // 등급도 따로 매긴다 — 한 칸으로 묶으면 한쪽만 올려 둔 사람이 나머지도
    // 올린 것으로 계산된다.
    //
    // 힘민지 쪽만 되짚을 수 있다("auto"). 기본 공격력에서 푼 총합에 그 몫이
    // 들어 있기 때문이다. 추가 피해 목장은 어디에도 안 드러나서 손으로 고른다.
    // 추가 피해 목장은 되짚을 길이 없다 — 게임이 추가 피해 총합을 어디에도
    // 안 알려 준다. 그래서 손으로 고르는데, 기본을 0으로 두면 목장을 올려 둔
    // 사람의 딜을 0.74% 낮게 잰다. 있는 쪽이 훨씬 흔하므로 1%로 시작한다.
    ranchDamage: 1,
    ranchMainStat: "auto",
    // 원정대 레벨 보상으로 붙는 힘민지. 장비 밖에서 오는 것이라 장비 합에
    // 없고, 그래서 목장을 되짚을 때 잔차에 섞여 목장을 부풀린다.
    // 게임의 원정대 창 '원정대 증가 효과'에 적혀 있는 값이다.
    expeditionMainStat: 1900,
    critStat: 0,
    specStat: 0,
    swiftStat: 0,
  },
  weapon: { quality: 0 },
  // 보석(작열·광휘). 쿨감만 쓴다 — 피해 증가형은 스킬에만 걸려 진화 배분을
  // 안 바꾼다. 레벨이 아니라 퍼센트를 든다: 보석마다 레벨이 달라서 하나로
  // 못 적고, 어느 스킬에 몇 레벨이 박혔는지에 따라 실효값이 달라지기 때문이다.
  jewel: { cooldown: 0 },
  // 깨달음·도약. 직업 코드와 찍은 레벨만 든다 — 수치는 표에 있다.
  // 탐색이 건드리지 않는다. 진화 140포인트와 달리 자주 갈아엎는 것이 아니다.
  // uptime — 줄마다의 유효율(%). 비어 있으면 100으로 읽는다. awakeningUptimeRate 참고.
  awakening: { job: 0, nodeLevels: {}, uptime: {} },
  // 파티 시너지. 내 것은 직업과 깨달음이 정하므로 여기엔 고른 것만 담는다.
  synergy: { rows: [], ownUptime: {} },
  engravings: {},
  // 어빌리티 스톤이 각인마다 얹은 레벨(1~4). 돌은 하나뿐이라 탐색이 안 굴린다.
  engravingStones: {},
  nodeLevels: {},
  baseEffects: [
    { id: makeId(), label: "카드 추가 피해", category: "damage:추가 피해", customCategory: "", amount: 0, formula: "", cap: "" },
    { id: makeId(), label: "각인/시너지 치적", category: "critRate", customCategory: "", amount: 0, formula: "", cap: "" },
    { id: makeId(), label: "추가 치명타 피해", category: "critDamage", customCategory: "", amount: 0, formula: "", cap: "" },
  ],
  // 특화가 미는 스킬 묶음 — 아이덴티티류. 줄은 게임의 특화 툴팁을 그대로 옮긴다.
  specBundles: [],
  selectedTier: "전체",
  setupName: "",
};

const MULTIPLICATIVE_DAMAGE_GROUPS = new Set(["주는 피해"]);

const SQRT_DAMAGE_GROUPS = new Set(["무기 공격력", "힘민지"]);

const ATTACK_CHAIN_GROUPS = new Set(["힘민지", "무기 공격력", "공격력", "시너지 공격력"]);

function damageGroupFactor(key, value) {
  const ratio = 1 + readNumber(value) / 100;
  if (!SQRT_DAMAGE_GROUPS.has(key)) return ratio;
  return ratio <= 0 ? 0 : Math.sqrt(ratio);
}

function normalizeSynergy(synergy) {
  const rows = Array.isArray(synergy?.rows) ? synergy.rows : legacySynergyRows(synergy?.picks);
  return {
    rows: normalizeSynergyRows(rows).map((row, index) => ({
      ...row, id: row.id || `syn-${index}`,
    })),
    ownUptime: normalizeUptimeMap(synergy?.ownUptime),
  };
}

function legacySynergyRows(picks) {
  const byJob = new Map();
  (Array.isArray(picks) ? picks : []).forEach(id => {
    const [job, node] = String(id).split(":");
    const code = readNumber(job);
    if (!getSynergyJob(code)) return;
    if (!byJob.has(code)) byJob.set(code, { job: code, nodes: [], uptime: {} });
    if (node) byJob.get(code).nodes.push(node);
  });
  return [...byJob.values()];
}

const STAGGER_DAMAGE_GROUPS = new Set(["무력화 대상 피해"]);

function getStaggerShare(convenience) {
  return clamp(readNumber(convenience?.staggerShare) / 100, 0, 1);
}

function normalizeArkGrid(arkGrid) {
  const cores = {};
  CHAOS_CORE_SLOTS.forEach(slot => {
    const chosen = arkGrid?.cores?.[slot.key] || {};
    const known = CHAOS_CORES.some(core => core.id === chosen.id);
    cores[slot.key] = {
      id: known ? chosen.id : "none",
      points: CHAOS_CORE_POINTS.includes(Math.round(readNumber(chosen.points)))
        ? Math.round(readNumber(chosen.points))
        : 20,
      stage: clamp(Math.round(readNumber(chosen.stage)), 0, CHAOS_CORE_STAGES.length - 1),
    };
  });
  // 옛 저장본은 gemLevel 하나만 들고 있다. 그건 추가 피해였다.
  const legacyGem = readNumber(arkGrid?.gemLevel);
  const gems = {};
  ARK_GRID_GEM_EFFECTS.forEach(effect => {
    const raw = arkGrid?.gems?.[effect.key] ?? (effect.key === "additional" ? legacyGem : 0);
    gems[effect.key] = clamp(Math.round(readNumber(raw)), 0, GEM_MAX_LEVEL);
  });
  return { cores, gems };
}

function applyCoreEffect(effect, stage, times, percentBonuses, damageGroups, flat) {
  const raw = Array.isArray(effect.amounts) ? effect.amounts[stage] : effect.amount;
  const amount = readNumber(raw) * times;
  if (amount === 0) return;

  if (effect.kind === "damage") {
    addDamageGroup(damageGroups, effect.key, amount);
    return;
  }
  if (effect.kind === "critOnlyDamage") {
    addCritOnlyDamage(percentBonuses, amount);
    return;
  }
  if (effect.kind === "flat") {
    addFlatBonus(flat, effect.key, amount);
    return;
  }
  percentBonuses[effect.key] = readNumber(percentBonuses[effect.key]) + amount;
}

function applyArkGridEffects(arkGrid, percentBonuses, damageGroups, flat) {
  const grid = normalizeArkGrid(arkGrid);

  CHAOS_CORE_SLOTS.forEach(slot => {
    const chosen = grid.cores[slot.key];
    const core = CHAOS_CORES.find(item => item.id === chosen.id);
    if (!core) return;

    // 포인트 구간은 누적이다. 17P를 고르면 10P와 14P 효과도 함께 붙는다.
    [10, 14, 17].forEach(threshold => {
      if (chosen.points < threshold) return;
      (core.thresholds[threshold] || []).forEach(effect => {
        applyCoreEffect(effect, chosen.stage, 1, percentBonuses, damageGroups, flat);
      });
    });

    // 18~20P는 1포인트마다 같은 값이 한 번씩 더 붙는다.
    const extra = clamp(chosen.points - 17, 0, 3);
    if (extra > 0) {
      core.perPoint.forEach(effect => {
        applyCoreEffect(effect, chosen.stage, extra, percentBonuses, damageGroups, flat);
      });
    }
  });

  ARK_GRID_GEM_EFFECTS.forEach(effect => {
    addDamageGroup(damageGroups, effect.group, arkGridGemDamage(effect.key, grid.gems[effect.key]));
  });
}

function applyCollectionEffects(collection, totalStats, damageGroups) {
  const source = { ...DEFAULT_STATE.collection, ...(collection || {}) };
  totalStats.critStat = readNumber(totalStats.critStat) + readNumber(source.critStat);
  totalStats.specStat = readNumber(totalStats.specStat) + readNumber(source.specStat);
  totalStats.swiftStat = readNumber(totalStats.swiftStat) + readNumber(source.swiftStat);
  // 추가 피해 목장. 힘민지 목장과 등급이 따로다.
  addDamageGroup(damageGroups, "추가 피해", resolveRanchDamage(collection || {}));
}

function applyWeaponEffects(weapon, damageGroups) {
  const quality = clamp(Math.round(readNumber(weapon?.quality)), 0, WEAPON_QUALITY_MAX);
  addDamageGroup(damageGroups, "추가 피해", weaponQualityDamage(quality));
}

const DAMAGE_MIX_KEYS = ["manaCooldown", "plainCooldown", "identityPlain", "identityMana"];

const DAMAGE_MIX_LABELS = {
  manaCooldown: "마나 O · 자체 쿨",
  plainCooldown: "마나 X · 자체 쿨",
  identityPlain: "마나 X · 아이덴티티",
  identityMana: "마나 O · 아이덴티티",
};

function normalizeDamageMix(convenience) {
  const mix = convenience?.damageMix;
  if (mix && typeof mix === "object") {
    const shares = {};
    let total = 0;
    DAMAGE_MIX_KEYS.forEach(key => {
      const value = Math.max(0, readNumber(mix[key]));
      shares[key] = value;
      total += value;
    });
    if (total > 0) return { shares, total, feederMana: mix.feederMana !== false };
  }
  const manaShare = clamp(readNumber(convenience?.manaShare ?? 100), 0, 100);
  return {
    shares: {
      manaCooldown: manaShare,
      plainCooldown: 0,
      identityPlain: 100 - manaShare,
      identityMana: 0,
    },
    total: 100,
    feederMana: true,
  };
}

const SPEC_BUNDLE_KINDS = [
  { value: "damage", label: "피해" },
  { value: "gain", label: "수급" },
  { value: "speed", label: "공속" },
  { value: "cooldown", label: "쿨감" },
];

function normalizeSpecBundles(list) {
  if (!Array.isArray(list)) return [];
  return list.map(bundle => ({
    id: bundle?.id || makeId(),
    name: typeof bundle?.name === "string" ? bundle.name : "",
    share: readNumber(bundle?.share),
    refSpec: readNumber(bundle?.refSpec),
    rows: (Array.isArray(bundle?.rows) ? bundle.rows : []).map(row => ({
      kind: SPEC_BUNDLE_KINDS.some(kind => kind.value === row?.kind) ? row.kind : "damage",
      base: readNumber(row?.base),
      amount: readNumber(row?.amount),
      // 값 두 개로 못 적는 꼴은 식으로 적는다 — 기공사의 "기본 × 증폭(특화)".
      formula: typeof row?.formula === "string" ? row.formula : "",
    })),
  }));
}

function specBundleValue(row, spec, refSpec, stats) {
  const text = String(row?.formula ?? "").trim();
  if (text) {
    const value = evaluateFormula(text, specBundleVariables(stats, spec));
    return value === null ? 0 : value;
  }
  const base = readNumber(row?.base);
  const at = readNumber(row?.amount);
  if (!(refSpec > 0)) return at;
  return base + (at - base) * (spec / refSpec);
}

function specBundleRowFactor(row, spec, refSpec, stats) {
  const atRef = specBundleValue(row, refSpec, refSpec, stats);
  if (row?.kind === "cooldown") {
    // 쿨감은 시전 횟수 1/(1−c)로 실린다. 모델의 쿨감 상한과 같은 80으로 막는다.
    const now = clamp(specBundleValue(row, spec, refSpec, stats), 0, 80) / 100;
    const ref = clamp(atRef, 0, 80) / 100;
    return (1 - ref) / (1 - now);
  }
  const now = 1 + specBundleValue(row, spec, refSpec, stats) / 100;
  const ref = 1 + atRef / 100;
  if (ref <= 0 || now <= 0) return 1;
  return now / ref;
}

function specBundleVariables(stats, spec) {
  return {
    "치명": readNumber(stats?.critStat),
    "특화": spec,
    "신속": readNumber(stats?.swiftStat),
    "제압": readNumber(stats?.dominationStat),
    "인내": readNumber(stats?.enduranceStat),
    "숙련": readNumber(stats?.expertiseStat),
  };
}

function specBundleBlend(bundles, stats) {
  const spec = readNumber(stats?.specStat);
  let blend = 1;
  const applied = [];
  normalizeSpecBundles(bundles).forEach(bundle => {
    const share = clamp(bundle.share, 0, 100) / 100;
    if (share <= 0 || bundle.rows.length === 0) return;
    const multiplier = bundle.rows.reduce(
      (acc, row) => acc * specBundleRowFactor(row, spec, bundle.refSpec, stats), 1,
    );
    blend += share * (multiplier - 1);
    applied.push({ id: bundle.id, name: bundle.name, share: share * 100, multiplier });
  });
  return { blend: Math.max(0, blend), applied };
}

function getManaShareRatio(convenience) {
  const { shares, total } = normalizeDamageMix(convenience);
  return (shares.manaCooldown + shares.identityMana) / total;
}

function getManaCooldownShareRatio(convenience) {
  const { shares, total, feederMana } = normalizeDamageMix(convenience);
  const identityPlain = feederMana ? shares.identityPlain : 0;
  return (shares.manaCooldown + shares.identityMana + identityPlain) / total;
}

function blendCooldownRemain(reduction, share) {
  const beta = clamp(readNumber(share), 0, 1);
  if (beta <= 0) return 1;
  const remain = Math.max(0, 1 - readNumber(reduction) / 100);
  if (remain <= 0) return 0;
  return 1 / (1 - beta + beta / remain);
}

function calculateMetrics(inputState) {
  const convenience = { ...DEFAULT_STATE.convenience, ...(inputState.convenience || {}) };
  const manaShare = getManaShareRatio(convenience);
  const accessories = normalizeAccessories(inputState.accessories);
  const bracelet = normalizeBracelet(inputState.bracelet);
  const totalStats = {
    critStat: readNumber(inputState.base.critStat),
    specStat: readNumber(inputState.base.specStat),
    swiftStat: readNumber(inputState.base.swiftStat),
    dominationStat: readNumber(inputState.base.dominationStat),
    enduranceStat: readNumber(inputState.base.enduranceStat),
    expertiseStat: readNumber(inputState.base.expertiseStat),
  };
  if (Object.hasOwn(totalStats, convenience.petStat)) {
    totalStats[convenience.petStat] += ARC_PASSIVE_CONSTANTS.petStatBonus;
  }
  const percentBonuses = {
    critRate: 0,
    critDamage: 0,
    attackSpeed: 0,
    attackSpeedOnly: 0,
    moveSpeedOnly: 0,
    cooldownReduction: 0,
    cooldownIncrease: 0,
    manaCooldownReduction: 0,
    skillCooldownReduction: 0,
    critOnlyDamage: 0,
  };
  const damageGroups = {};
  // 평면 증가는 여기 모아 둔다. 퍼센트로 바꾸려면 기준값이 필요한데,
  // 그 나눗셈은 출처를 다 걷은 뒤 한 번만 하는 편이 읽기 쉽다.
  const flatBonuses = emptyFlatBonuses();
  const specials = {
    bluntThorn: 0,
    sonicBreakthrough: 0,
  };
  let pointsUsed = 0;

  NODE_LIBRARY.forEach(node => {
    const level = clamp(Math.round(inputState.nodeLevels?.[node.id] || 0), 0, node.maxLevel);
    pointsUsed += level * getNodeCost(node);
    node.effects.forEach(effect => {
      applyEffect(effect, level, totalStats, percentBonuses, damageGroups, specials, manaShare, inputState.settings);
    });
  });

  // 속도를 재료로 삼는 항목은 여기서 값을 정할 수 없다. 모아 두었다가
  // finalizeMetrics가 속도를 확정한 뒤에 건다.
  const conversions = [];
  (inputState.baseEffects || []).forEach(effect => {
    applyBaseEffect(effect, percentBonuses, damageGroups, conversions, flatBonuses);
  });

  const accessoryBonuses = calculateAccessoryBonuses(accessories);
  percentBonuses.critRate += accessoryBonuses.critRate;
  percentBonuses.critDamage += accessoryBonuses.critDamage;
  addDamageGroup(damageGroups, "추가 피해", accessoryBonuses.additionalDamage);
  addDamageGroup(damageGroups, "주는 피해", accessoryBonuses.dealtDamage);
  addDamageGroup(damageGroups, "공격력", accessoryBonuses.attackPower);
  addDamageGroup(damageGroups, "무기 공격력", accessoryBonuses.weaponAttack);

  const karmaDamage = clamp(Math.round(readNumber(convenience.evolutionKarmaRank)), 0, 6);
  addDamageGroup(damageGroups, "진화형 피해", karmaDamage);
  // 정열의 춤사위 — 서폿 아크 그리드. 진화 카르마와 같은 그룹이라 합연산이다.
  addDamageGroup(damageGroups, "진화형 피해", passionDanceAmount(convenience.passionDance));

  const goddessNodeLevel = clamp(
    Math.round(readNumber(inputState.nodeLevels?.["e2-goddess-blessing"])),
    0,
    3,
  );
  if (convenience.goddessBlessing) {
    const goddessNodeSpeed = goddessNodeLevel * 3;
    percentBonuses.attackSpeed += Math.max(0, ARC_PASSIVE_CONSTANTS.goddessBlessingSpeed - goddessNodeSpeed);
  }
  if (convenience.feast) {
    percentBonuses.attackSpeed += ARC_PASSIVE_CONSTANTS.feastSpeed;
  }
  applyFoodEffects(convenience.food, percentBonuses, flatBonuses);

  if (inputState.settings.backAttack) {
    percentBonuses.critRate += ARC_PASSIVE_CONSTANTS.backAttackCritRate;
    addDamageGroup(damageGroups, "주는 피해", ARC_PASSIVE_CONSTANTS.backAttackDamage);
  }
  if (inputState.settings.headAttack) {
    addDamageGroup(damageGroups, "헤드어택 피해", ARC_PASSIVE_CONSTANTS.headAttackDamage);
  }

  applyArkGridEffects(inputState.arkGrid, percentBonuses, damageGroups, flatBonuses);
  const awakening = applyAwakeningEffects(inputState.awakening, percentBonuses, damageGroups, conversions);
  const synergy = applySynergyEffects(inputState, percentBonuses, damageGroups);
  applyCollectionEffects(inputState.collection, totalStats, damageGroups);
  applyWeaponEffects(inputState.weapon, damageGroups);
  applyBraceletEffects(bracelet, inputState.settings, totalStats, percentBonuses, damageGroups, flatBonuses);

  const engravingSpecials = applyEngravingEffects(
    inputState.engravings,
    percentBonuses,
    damageGroups,
    manaShare,
    inputState.settings,
    inputState.engravingStones,
  );

  // 걷은 평면 증가를 퍼센트로 바꾼다. 기준값이 비어 있으면 못 센 목록만 남는다.
  const attack = assembleAttack(inputState);
  const droppedFlat = applyFlatAttackBonuses(flatBonuses, attack, damageGroups);

  return finalizeMetrics({
    settings: inputState.settings,
    specDamagePer100: readNumber(inputState.base.specDamagePer100),
    critDamageBonus: 0,
    totalStats,
    percentBonuses,
    damageGroups,
    specials,
    engravingSpecials,
    pointsUsed,
    accessoryBonuses,
    manaCooldownShare: getManaCooldownShareRatio(convenience),
    staggerShareRatio: getStaggerShare(convenience),
    conversions,
    attack,
    flatBonuses,
    droppedFlat,
    awakening,
    synergy,
    jewelCooldownPercent: inputState.jewel?.cooldown,
    specBundles: inputState.specBundles,
    support: inputState?.convenience?.support,
  });
}

function finalizeMetrics(context) {
  const {
    settings,
    specDamagePer100,
    critDamageBonus,
    totalStats,
    percentBonuses,
    damageGroups,
    specials,
    engravingSpecials,
    pointsUsed,
    accessoryBonuses,
    manaCooldownShare,
    staggerShareRatio,
    conversions,
    attack,
    flatBonuses,
    droppedFlat,
    awakening,
    synergy,
    jewelCooldownPercent,
    specBundles,
    support,
  } = context;

  const manaCooldownCoverage = clamp(readNumber(manaCooldownShare ?? 1), 0, 1);
  const specDamage = (totalStats.specStat / 100) * readNumber(specDamagePer100);
  if (specDamage !== 0) {
    addDamageGroup(damageGroups, "특화 효율", specDamage);
  }

  const critRateFromStat = totalStats.critStat * ARC_PASSIVE_CONSTANTS.critRatePerCrit;
  const attackSpeedFromSwift = totalStats.swiftStat * ARC_PASSIVE_CONSTANTS.attackSpeedPerSwift;
  const cooldownFromSwift = totalStats.swiftStat * ARC_PASSIVE_CONSTANTS.cooldownPerSwift;
  const sharedSpeedBonus = attackSpeedFromSwift + percentBonuses.attackSpeed;
  const attackSpeed = sharedSpeedBonus + percentBonuses.attackSpeedOnly;
  const moveSpeedBonus = sharedSpeedBonus + percentBonuses.moveSpeedOnly;
  // 2단 — 속도·특성을 읽어 치명타/쿨감을 만드는 식. 치적이 정해지기 전에 건다.
  // 예) 기민함: 기본 공격 속도 증가량 %의 120%만큼 치명타 피해
  const stage1Variables = buildFormulaVariables(attackSpeed, moveSpeedBonus, totalStats, null);
  const stage2Results = applyFormulaEffects(
    conversions, stage1Variables, percentBonuses, damageGroups, 2,
  );

  const critRateRaw = Math.max(
    critRateFromStat + percentBonuses.critRate,
    engravingSpecials.critRateMinimum,
  );
  const attackSpeedRaw = 100 + attackSpeed;
  const moveSpeedRaw = 100 + moveSpeedBonus;
  const attackSpeedExcess = Math.max(0, attackSpeedRaw - 140);
  const moveSpeedExcess = Math.max(0, moveSpeedRaw - 140);
  const appliedAttackSpeedBonus = clamp(attackSpeed, -99, 40);
  const attackMoveSpeed = 100 + appliedAttackSpeedBonus;
  const moveSpeed = 100 + clamp(moveSpeedBonus, -99, 40);
  const raidCaptainDamage = clamp(moveSpeedBonus, 0, 40) * engravingSpecials.raidCaptainRate / 100;
  addDamageGroup(damageGroups, "주는 피해", raidCaptainDamage);
  // 쿨감은 피해 그룹과 같은 규칙이다. 네 그룹이 있고, 그룹 안에서는 더하고
  // 그룹끼리는 곱한다. 넷 다 적용된다 — 어느 하나를 골라 버리지 않는다.
  //   신속 · 직접 입력(일반) · 끝마/무마 · 최훈/타지
  // 끝마/무마만 예외다. 마나를 쓰는 스킬에만 붙으므로, 그 혜택을 받는 딜
  // 비중만큼만 사이클이 당겨진다. 나머지 세 그룹은 전 스킬에 걸린다.
  const manaCooldownRemain = blendCooldownRemain(
    percentBonuses.manaCooldownReduction,
    manaCooldownCoverage,
  );
  const cooldownGroups = {
    swift: cooldownFromSwift,
    generic: percentBonuses.cooldownReduction,
    mana: (1 - manaCooldownRemain) * 100,
    skill: percentBonuses.skillCooldownReduction,
    jewel: clamp(readNumber(jewelCooldownPercent), 0, 100),
  };
  // 곱은 "남은 쿨타임"으로 계산해야 맞는다. 감소율을 더하면 부풀려진다.
  const cooldownRemain = COOLDOWN_GROUP_KEYS.reduce(
    (acc, key) => acc * (1 - readNumber(cooldownGroups[key]) / 100),
    1,
  );
  const cooldownReduction = (1 - cooldownRemain) * 100;
  const cooldownGroupLabel = getCooldownGroupLabel(cooldownGroups);
  const bluntThornBonus = calculateBluntThornBonus(specials.bluntThorn, critRateRaw);
  const sonicBreakdown = calculateSonicBreakthroughBonus(
    specials.sonicBreakthrough,
    attackSpeed,
    moveSpeedBonus,
  );
  const sonicBonus = sonicBreakdown.damage;
  if (bluntThornBonus.damage > 0) {
    addDamageGroup(damageGroups, "진화형 피해", bluntThornBonus.damage);
  }
  if (sonicBonus > 0) {
    addDamageGroup(damageGroups, "진화형 피해", sonicBonus);
  }

  const critCap = specials.bluntThorn > 0 ? 80 : 100;
  const critRateCapped = clamp(critRateRaw, 0, critCap);
  const critDamage = Math.max(
    100,
    ARC_PASSIVE_CONSTANTS.baseCritDamage + readNumber(critDamageBonus) + percentBonuses.critDamage,
  );

  // 3단 — 치명타까지 정해진 뒤에 피해 그룹을 만드는 식.
  // 예) 성검 개방: 모든 치명타 발생 확률 1%당 주는 피해 0.55% (최대 55%)
  const stage2Variables = buildFormulaVariables(attackSpeed, moveSpeedBonus, totalStats, {
    rateCapped: critRateCapped, rateRaw: critRateRaw, damage: critDamage,
  });
  const stage3Results = applyFormulaEffects(
    conversions, stage2Variables, percentBonuses, damageGroups, 3,
  );
  const formulaResults = [...stage2Results, ...stage3Results].filter(Boolean);

  // 제압은 무력화 대상 피해로 바뀐다. 특성이 다 모인 뒤에 한 번 얹는다.
  const staggerShare = clamp(readNumber(staggerShareRatio ?? 0), 0, 1);
  if (staggerShare > 0) {
    addDamageGroup(
      damageGroups, "무력화 대상 피해",
      readNumber(totalStats.dominationStat) * ARC_PASSIVE_CONSTANTS.staggerDamagePerDomination,
    );
  }

  const critChance = critRateCapped / 100;
  const critOnlyMultiplier = 1 + percentBonuses.critOnlyDamage / 100;
  const critFactor = (1 - critChance) + critChance * (critDamage / 100) * critOnlyMultiplier;

  /**
   * 공격력 사슬 — 게임 수식의 A~E.
   *
   *   A 힘민지 = 총합 × (1 + 힘민지 증가율)
   *   B 무공   = 총합 × (1 + 무공 증가율)
   *   C 순수   = √(A × B ÷ 6)
   *   D 기본   = C × (1 + 보석 기본 공격력 + 어빌리티 스톤)
   *   E 최종   = (D + 공격력 평면 + 서폿 공증) × (1 + 공격력 증가율) × (1 + 투지 강화)
   *
   * 한동안 이 사슬이 통째로 없었다. 힘민지·무기 공격력은 '피해 그룹'에 퍼센트로
   * 담고 √를 그룹 배수 쪽에서 흉내 냈고(SQRT_DAMAGE_GROUPS), 절대값은 아예 안
   * 실었다. 진화 배분만 견줄 때는 그래도 됐다 — 공격력이 모든 후보에 똑같이
   * 곱해져 순위를 안 바꾸니까.
   *
   * 그런데 악세를 견주려면 그게 안 된다. 주스탯 11,000을 얹어도 지수가 0.000%
   * 움직이고, 평면 무공을 더하면 오히려 내려갔다(평면을 퍼센트로 바꿀 때 쓰는
   * 분모가 같이 커져서). 사슬을 제대로 세우면 그 둘이 제자리를 찾는다.
   *
   * 비는 그대로다 — C = √(A×B÷6)이 √를 원래대로 처리하므로, 진화 배분끼리의
   * 순위와 증감은 예전과 같다. 달라지는 것은 지수의 눈금뿐이다.
   */
  //
  // 연마 퍼센트는 악세 모델(귀걸이 상중하)이 들고 있다. assembleAttack이 쓰는
  // attack.weaponPercent와 같은 것이라, 둘 다 곱하면 3.6%가 두 번 실린다 —
  // 그래서 여기서는 조립한 값이 아니라 평면(weaponBase)에서 다시 세운다.
  //
  // 기준값을 모르면 사슬은 아예 안 선다.
  //
  // 예전에는 평면만 들고도 값을 만들었다. 사전 세팅에 공격력을 안 적은 채
  // 팔찌 무공 +9,000만 있으면 그게 무공 전부가 되어, 팔찌를 빼면 딜이 0이
  // 되고 "이 팔찌가 +162%"라는 답이 나왔다. 모르는 것은 모른다고 해야 한다 —
  // 그 사실은 droppedFlat이 이미 따로 알린다.
  const mainBase = Math.max(0, readNumber(attack.mainBase));
  const weaponBase = Math.max(0, readNumber(attack.weaponBase));
  const chainKnown = mainBase > 0 && weaponBase > 0;
  const mainFlatSum = chainKnown ? mainBase + readNumber(flatBonuses.mainStat) : 0;
  const mainStatTotal = mainFlatSum
    * (1 + readNumber(attack.mainScalePercent) / 100)
    * (1 + readNumber(damageGroups["힘민지"]) / 100);
  const weaponFlatSum = chainKnown ? weaponBase + readNumber(flatBonuses.weaponAttack) : 0;
  const weaponTotal = weaponFlatSum
    * (1 + (readNumber(attack.karmaWeaponPercent) + readNumber(damageGroups["무기 공격력"])) / 100);
  const pureAttack = Math.sqrt(Math.max(0, mainStatTotal * weaponTotal / 6));
  const baseAttack = (pureAttack + Math.max(0, readNumber(attack?.baseFlat)))
    * (1 + Math.max(0, readNumber(attack?.baseScalePercent)) / 100);
  // 서폿 공증은 퍼센트가 아니라 평면이다 — 버프 시전자의 기본 공격력 × 22% ×
  // (1 + 아군 공격력 강화 효과 증가)가 내 기본 공격력에 더해진다. 괄호 안에
  // 들어가기 때문에 무공·힘민지를 희석한다. 곱연산 그룹으로 두면 그 희석이
  // 일어나지 않아서, 서폿이 붙어도 귀걸이 무공의 값어치가 그대로 나온다.
  const supportAttack = chainKnown ? supportAttackPower(support, baseAttack) : 0;
  const finalAttack = chainKnown
    ? (baseAttack + readNumber(flatBonuses.attackPower) + supportAttack)
      * (1 + readNumber(damageGroups["공격력"]) / 100)
      * (1 + readNumber(damageGroups["시너지 공격력"]) / 100)
    : 0;

  // 위 셋은 사슬이 삼켰다. 피해 배수에서 또 곱하면 두 번이다.

  // 평시 배수와 무력화 배수를 따로 접는다. 무력화 쪽은 대난투 비중만큼만 섞는다.
  // 사슬이 서면 그 넷은 사슬이 삼킨다. 안 서면(공격력을 모르면) 예전처럼
  // 여기서 곱한다 — 안 그러면 귀걸이 연마가 통째로 사라진다.
  const plainMultiplier = Object.entries(damageGroups)
    .filter(([key]) => !STAGGER_DAMAGE_GROUPS.has(key) && !(chainKnown && ATTACK_CHAIN_GROUPS.has(key)))
    .reduce((acc, [key, value]) => acc * damageGroupFactor(key, value), 1);
  const staggerMultiplier = Object.entries(damageGroups)
    .filter(([key]) => STAGGER_DAMAGE_GROUPS.has(key))
    .reduce((acc, [key, value]) => acc * damageGroupFactor(key, value), 1);
  const staggerBlend = 1 - staggerShare + staggerShare * staggerMultiplier;
  // 특화 묶음. 특성 합이 다 선 뒤의 특화로 계산해야 탐색 후보마다 제대로 갈린다.
  const specBundleResult = specBundleBlend(specBundles, totalStats);
  const damageMultiplier = plainMultiplier * staggerBlend * specBundleResult.blend;
  const cooldownIncrease = Math.max(0, percentBonuses.cooldownIncrease);
  // 쿨감은 언제나 DPS에 실린다. 끄는 스위치가 있었는데, 끄면 DPS가 한 방 딜과
  // 같아져서 곡선이 점 하나로 무너진다 — 계산기가 하는 일이 사라진다.
  const cooldownFactor = 1 / ((1 - clamp(cooldownReduction, 0, 80) / 100) * (1 + cooldownIncrease / 100));
  // 공속을 DPS에 곱하지 않는다. 공속이 곧 딜 사이클 단축이라는 근거가 약하고,
  // 공속의 실제 이득은 음속 돌파의 진화형 피해 전환으로만 반영한다.
  const attackSpeedFactor = 1;
  // 지수는 공격력 사슬 위에 선다. 1,000으로 나누는 것은 눈금일 뿐이고 —
  // 공격력을 모르는 상태(불러오기 전)에서는 사슬이 0이라 지수가 통째로 0이
  // 되므로, 그때는 예전처럼 100을 쓴다. 견주는 데는 비만 필요하다.
  const attackScale = finalAttack > 0 ? finalAttack / 1000 : 100;
  const damageIndex = attackScale * critFactor * damageMultiplier;
  const dpsIndex = damageIndex * cooldownFactor * attackSpeedFactor;

  /**
   * 대난투 지수 — 무력화 가중을 100%로 둔 한 방 딜.
   *
   * 사용자의 '대난투 딜 비중'과 무관하게 언제나 잰다. 그 칸은 "내 로테이션에서
   * 대난투가 몇 %냐"를 적는 자리이고, 이 지수는 "대난투만 재면 누가 제일 센가"라
   * 서 묻는 것이 다르다.
   *
   * 비중이 0이면 무력화 그룹이 damageGroups에 아예 안 들어간다. 그 몫을 여기서
   * 따로 얹는다 — damageGroups 자체는 안 건드린다. 계기판이 읽는 것이라,
   * 비중을 0으로 둔 사람에게 없는 줄이 보이면 그게 거짓말이 된다.
   */
  const staggerFullGroups = { ...damageGroups };
  if (!(staggerShare > 0)) {
    addDamageGroup(
      staggerFullGroups, "무력화 대상 피해",
      readNumber(totalStats.dominationStat) * ARC_PASSIVE_CONSTANTS.staggerDamagePerDomination,
    );
  }
  const staggerFullMultiplier = Object.entries(staggerFullGroups)
    .filter(([key]) => STAGGER_DAMAGE_GROUPS.has(key))
    .reduce((acc, [key, value]) => acc * damageGroupFactor(key, value), 1);
  const staggerIndex = 100 * critFactor * plainMultiplier * staggerFullMultiplier * specBundleResult.blend;

  return {
    totalStats,
    percentBonuses,
    damageGroups,
    specials,
    engravingSpecials,
    bluntThornBonus,
    sonicBonus,
    sonicBreakdown,
    pointsUsed,
    critRateFromStat,
    // 신속이 얼마나 속도로 환산됐는지 — 계기판의 공이속 출처 목록에 필요하다.
    attackSpeedFromSwift,
    // 식으로 적은 효과들의 실제 결과. 계기판이 출처로 적는다.
    formulaResults,
    formulaVariables: stage2Variables,
    critRateRaw,
    critRateCapped,
    critDamage,
    attackSpeed,
    attackSpeedRaw,
    attackSpeedExcess,
    attackMoveSpeed,
    moveSpeedBonus,
    moveSpeedRaw,
    moveSpeedExcess,
    moveSpeed,
    raidCaptainDamage,
    accessoryBonuses,
    cooldownGroups,
    cooldownGroupLabel,
    // 끝마/무마의 "깎이기 전" 값과 그 축소 비중 — 계기판이 근거를 보여줘야 한다.
    manaCooldownRaw: readNumber(percentBonuses.manaCooldownReduction),
    manaCooldownShare: manaCooldownCoverage,
    cooldownReduction,
    cooldownIncrease,
    critOnlyDamage: percentBonuses.critOnlyDamage,
    critFactor,
    // 공격력 사슬 — 게임 수식의 A~E. 계기판과 검산이 읽는다.
    mainStatTotal,
    weaponTotal,
    pureAttack,
    baseAttack,
    supportAttack,
    finalAttack,
    damageMultiplier,
    plainMultiplier,
    staggerMultiplier,
    staggerShare,
    specBundleFactor: specBundleResult.blend,
    specBundleResults: specBundleResult.applied,
    cooldownFactor,
    attackSpeedFactor,
    damageIndex,
    dpsIndex,
    staggerIndex,
    // 공격력 축. 지수에는 곱하지 않는다 — 지수는 어디까지나 상대값이고,
    // 절대 데미지를 내려면 스킬 계수가 있어야 하는데 그건 이 계산기 밖이다.
    // 여기 있는 값은 평면 증가를 퍼센트로 바꾸는 데에만 쓰이고, 계기판이
    // 근거로 적는다.
    attack: attack ?? { weaponAttack: 0, mainStat: 0, flatAttack: 0 },
    baseAttackPower: baseAttackPower(attack),
    flatBonuses: flatBonuses ?? emptyFlatBonuses(),
    // 기준값이 없어 버린 평면 증가들. 조용히 빠지면 왜 안 맞는지 모른다.
    droppedFlat: droppedFlat ?? [],
    // 깨달음·도약 — 무엇이 들어갔고 무엇이 안 들어갔는지.
    awakening: awakening ?? { applied: [], skipped: [] },
    synergy: synergy ?? { own: null, rows: [], lines: [], combatCount: 0, over: false },
  };
}

function addCritOnlyDamage(percentBonuses, amount) {
  const added = readNumber(amount);
  if (added === 0) return;
  const before = readNumber(percentBonuses.critOnlyDamage);
  percentBonuses.critOnlyDamage = ((1 + before / 100) * (1 + added / 100) - 1) * 100;
}

function applyEffect(effect, level, totalStats, percentBonuses, damageGroups, specials, manaShare, settings) {
  if (effect.kind === "note") return;
  if (effect.kind === "special") {
    if (level > 0) specials[effect.key] = Math.max(specials[effect.key] || 0, level);
    return;
  }
  // 노드 하나 안에서도 효과마다 조건이 다를 수 있다. 일격이 그렇다 —
  // 치적은 전체, 치피는 방향성 스킬 한정.
  if (!isDirectionalConditionActive(effect.condition, settings)) return;

  const amount = readNumber(effect.amount) * level * (effect.manaOnly ? manaShare : 1);
  if (amount === 0) return;

  if (effect.kind === "stat") {
    totalStats[effect.key] = readNumber(totalStats[effect.key]) + amount;
    return;
  }

  if (effect.kind === "damage") {
    addDamageGroup(damageGroups, effect.key, amount);
    return;
  }

  if (effect.kind === "critOnlyDamage") {
    addCritOnlyDamage(percentBonuses, amount);
    return;
  }

  percentBonuses[effect.key] = readNumber(percentBonuses[effect.key]) + amount;
}

function applyBaseEffect(effect, percentBonuses, damageGroups, conversions, flat) {
  const rate = effectUptimeRate(effect);
  if (typeof effect.formula === "string" && effect.formula.trim()) {
    if (Array.isArray(conversions)) {
      conversions.push({
        formula: effect.formula,
        // 게임 노드는 대개 "최대 55%까지" 같은 상한을 함께 갖는다. 식 안에
        // min()을 쓰게 하는 것보다 칸을 하나 두는 편이 읽고 고치기 쉽다.
        cap: effect.cap,
        category: effect.category,
        customCategory: effect.customCategory,
        label: effect.label,
        // 유효율은 식이 낸 결과에 곱한다. 상한은 그대로 둔다 — 상한은 그 값에서
        // 잘린다는 뜻이지 유효율만큼 같이 낮아지는 것이 아니다.
        uptime: rate,
      });
    }
    return;
  }

  const amount = readNumber(effect.amount) * rate;
  if (amount === 0) return;

  if (effect.category === "customDamage") {
    const label = (effect.customCategory || effect.label || "기타 피해").trim();
    addDamageGroup(damageGroups, label, amount);
    return;
  }

  if (effect.category.startsWith("damage:")) {
    const label = effect.category.slice("damage:".length);
    addDamageGroup(damageGroups, label, amount);
    return;
  }

  // 퍼센트가 아니라 숫자로 붙는 것들 — 팔찌 무공 +9,000 같은. 기준값을 만나야
  // 퍼센트가 되므로 여기서는 모으기만 한다.
  if (effect.category.startsWith("flat:")) {
    addFlatBonus(flat, effect.category.slice("flat:".length), amount);
    return;
  }

  if (effect.category === "critOnlyDamage") {
    addCritOnlyDamage(percentBonuses, amount);
    return;
  }

  percentBonuses[effect.category] = readNumber(percentBonuses[effect.category]) + amount;
}

function effectUptimeRate(effect) {
  const value = effect?.uptime;
  if (value === undefined || value === null || value === "") return 1;
  return clamp(readNumber(value), 0, 100) / 100;
}

const FORMULA_VARIABLES = [
  { name: "공격속도", hint: "상한 40% 적용", stage: 1 },
  { name: "이동속도", hint: "상한 40% 적용", stage: 1 },
  { name: "공격속도합", hint: "상한 전", stage: 1 },
  { name: "이동속도합", hint: "상한 전", stage: 1 },
  { name: "치명", hint: "특성 수치", stage: 1 },
  { name: "특화", hint: "특성 수치", stage: 1 },
  { name: "신속", hint: "특성 수치", stage: 1 },
  { name: "제압", hint: "특성 수치", stage: 1 },
  { name: "인내", hint: "특성 수치", stage: 1 },
  { name: "숙련", hint: "특성 수치", stage: 1 },
  { name: "치명타적중률", hint: "상한 적용", stage: 2 },
  { name: "치명타적중률합", hint: "상한 전", stage: 2 },
  { name: "치명타피해", hint: "합계", stage: 2 },
];

function getFormulaStage(category) {
  const key = String(category);
  if (key === "attackSpeedOnly" || key === "moveSpeedOnly" || key === "attackSpeed") return 0;
  if (key === "customDamage" || key.startsWith("damage:")) return 3;
  return 2;
}

function evaluateFormula(text, variables) {
  const src = String(text ?? "");
  let at = 0;

  const skip = () => { while (at < src.length && /\s/.test(src[at])) at += 1; };

  function primary() {
    skip();
    if (src[at] === "(") {
      at += 1;
      const value = expression();
      skip();
      if (src[at] !== ")") throw new Error("괄호가 닫히지 않았습니다");
      at += 1;
      return value;
    }
    if (src[at] === "-") { at += 1; return -primary(); }
    if (src[at] === "+") { at += 1; return primary(); }

    if (src.startsWith("{{", at)) {
      const end = src.indexOf("}}", at);
      if (end < 0) throw new Error("변수 괄호가 닫히지 않았습니다");
      const name = src.slice(at + 2, end).trim();
      at = end + 2;
      if (!Object.hasOwn(variables, name)) throw new Error(`모르는 변수: ${name}`);
      return readNumber(variables[name]);
    }

    const fn = /^(min|max)\s*\(/i.exec(src.slice(at));
    if (fn) {
      at += fn[0].length;
      const left = expression();
      skip();
      if (src[at] !== ",") throw new Error("min/max에는 값이 둘 필요합니다");
      at += 1;
      const right = expression();
      skip();
      if (src[at] !== ")") throw new Error("괄호가 닫히지 않았습니다");
      at += 1;
      return fn[1].toLowerCase() === "min" ? Math.min(left, right) : Math.max(left, right);
    }

    // 120% 처럼 퍼센트로 적는 편이 읽기 쉽다. 숫자 뒤에서만 허용한다.
    const number = /^\d+(\.\d+)?%?/.exec(src.slice(at));
    if (number) {
      at += number[0].length;
      const raw = Number(number[0].replace("%", ""));
      return number[0].endsWith("%") ? raw / 100 : raw;
    }
    throw new Error("읽을 수 없는 글자입니다");
  }

  function term() {
    let value = primary();
    for (;;) {
      skip();
      if (src[at] === "*") { at += 1; value *= primary(); continue; }
      if (src[at] === "/") {
        at += 1;
        const divisor = primary();
        value = divisor === 0 ? 0 : value / divisor;
        continue;
      }
      return value;
    }
  }

  function expression() {
    let value = term();
    for (;;) {
      skip();
      if (src[at] === "+") { at += 1; value += term(); continue; }
      if (src[at] === "-") { at += 1; value -= term(); continue; }
      return value;
    }
  }

  try {
    if (!src.trim()) return null;
    const value = expression();
    skip();
    if (at !== src.length) throw new Error("식 뒤에 남은 글자가 있습니다");
    return Number.isFinite(value) ? value : null;
  } catch {
    return null;
  }
}

function buildFormulaVariables(attackSpeed, moveSpeedBonus, totalStats, crit) {
  return {
    "공격속도": clamp(readNumber(attackSpeed), 0, 40),
    "이동속도": clamp(readNumber(moveSpeedBonus), 0, 40),
    "공격속도합": readNumber(attackSpeed),
    "이동속도합": readNumber(moveSpeedBonus),
    "치명": readNumber(totalStats?.critStat),
    "특화": readNumber(totalStats?.specStat),
    "신속": readNumber(totalStats?.swiftStat),
    "제압": readNumber(totalStats?.dominationStat),
    "인내": readNumber(totalStats?.enduranceStat),
    "숙련": readNumber(totalStats?.expertiseStat),
    // 2단. 치명타가 정해지기 전에 부르면 없는 채로 남고, 그 식은 '모르는 변수'로
    // 걸러진다 — 조용히 0이 되지 않는다.
    ...(crit ? {
      "치명타적중률": readNumber(crit.rateCapped),
      "치명타적중률합": readNumber(crit.rateRaw),
      "치명타피해": readNumber(crit.damage),
    } : {}),
  };
}

function applyFormulaEffects(conversions, variables, percentBonuses, damageGroups, stage) {
  if (!Array.isArray(conversions)) return [];

  return conversions.map(item => {
    const itemStage = getFormulaStage(item.category);
    // 속도를 대상으로 삼는 식은 아예 걸지 않는다. 속도가 정해진 뒤에 걸리므로
    // 되먹임이 없어 조용히 아무 일도 안 일어난 것처럼 보이기 때문이다.
    if (itemStage === 0) return { ...item, amount: 0, invalid: true, reason: "속도는 대상이 될 수 없습니다" };
    if (itemStage !== stage) return null;

    const value = evaluateFormula(item.formula, variables);
    // 식이 깨졌으면 0으로 두되 그 사실을 남긴다. 조용히 빠지면 왜 안 맞는지 모른다.
    const raw = value === null ? 0 : value;
    const cap = readNumber(item.cap);
    const capped = item.cap !== "" && item.cap !== null && item.cap !== undefined && raw > cap;
    // 상한을 먼저 먹이고 유효율을 곱한다. 게임의 상한은 그 값에서 잘린다는
    // 뜻이지 "실리는 시간만큼 상한도 낮아진다"는 뜻이 아니다.
    const rate = item.uptime === undefined ? 1 : clamp(readNumber(item.uptime), 0, 1);
    const amount = (capped ? cap : raw) * rate;
    const applied = {
      ...item, amount, raw, capped,
      invalid: value === null,
      reason: value === null ? "식을 읽을 수 없습니다" : "",
    };

    if (amount === 0) return applied;
    if (item.category === "customDamage") {
      addDamageGroup(damageGroups, (item.customCategory || item.label || "기타 피해").trim(), amount);
    } else if (String(item.category).startsWith("damage:")) {
      addDamageGroup(damageGroups, String(item.category).slice("damage:".length), amount);
    } else if (item.category === "critOnlyDamage") {
      addCritOnlyDamage(percentBonuses, amount);
    } else {
      percentBonuses[item.category] = readNumber(percentBonuses[item.category]) + amount;
    }
    return applied;
  });
}

function applyEngravingEffects(engravingState, percentBonuses, damageGroups, manaShare, settings, stones) {
  const engravingSpecials = {
    critRateMinimum: 0,
    raidCaptainRate: 0,
  };

  ENGRAVING_LIBRARY.forEach(engravingItem => {
    const tierIndex = getEngravingTierIndex(engravingState?.[engravingItem.id]);
    if (tierIndex < 0) return;
    applyEngravingTier(engravingItem, tierIndex, percentBonuses, damageGroups, engravingSpecials, manaShare, settings, stones?.[engravingItem.id]);
  });

  return engravingSpecials;
}

function applyEngravingTier(engravingItem, tierIndex, percentBonuses, damageGroups, engravingSpecials, manaShare, settings, stoneLevel = 0) {
  // Directional engravings follow the same 백어택/헤드어택 gating as bracelets,
  // so head-attack and back-attack effects can never stack on one hit.
  if (!isDirectionalConditionActive(engravingItem.condition, settings)) return;

  const put = (kind, key, amount) => {
    if (kind === "damage") { addDamageGroup(damageGroups, key, amount); return; }
    if (kind === "percent") { percentBonuses[key] = readNumber(percentBonuses[key]) + amount; return; }
    if (kind === "special") engravingSpecials[key] = Math.max(readNumber(engravingSpecials[key]), amount);
  };

  engravingItem.effects.forEach(effect => {
    const amount = engravingAmount(effect.amounts, tierIndex) * (effect.manaOnly ? manaShare : 1);
    put(effect.kind, effect.key, amount);
  });

  // 어빌리티 스톤이 얹는 몫. 단계 사다리와 따로 더해진다.
  const stone = engravingStoneAmount(engravingItem.id, stoneLevel, tierIndex);
  if (stone) put(stone.kind, stone.key, stone.amount * (stone.manaOnly ? manaShare : 1));
}

function getEngravingTierIndex(value) {
  return ENGRAVING_TIERS.findIndex(tier => tier.value === value);
}

function normalizeBracelet(bracelet) {
  const stats = BRACELET_STAT_FIELDS.reduce((result, item) => {
    result[item.key] = clamp(Math.round(readNumber(bracelet?.stats?.[item.key])), 0, 120);
    return result;
  }, {});
  const effects = {};

  BRACELET_EFFECTS.forEach(item => {
    const grade = bracelet?.effects?.[item.id];
    if (getBraceletGradeIndex(grade) >= 0) effects[item.id] = grade;
  });

  return { stats, mainStat: Math.max(0, Math.round(readNumber(bracelet?.mainStat))), effects };
}

function applyBraceletEffects(bracelet, settings, totalStats, percentBonuses, damageGroups, flat) {
  BRACELET_STAT_FIELDS.forEach(item => {
    totalStats[item.key] = readNumber(totalStats[item.key]) + readNumber(bracelet.stats[item.key]);
  });
  // 힘민지는 평면으로 붙는다. 기준값(사전 세팅의 공격력)을 만나야 퍼센트가 된다.
  addFlatBonus(flat, "mainStat", readNumber(bracelet.mainStat));

  BRACELET_EFFECTS.forEach(item => {
    const gradeIndex = getBraceletGradeIndex(bracelet.effects[item.id]);
    if (gradeIndex < 0 || !isDirectionalConditionActive(item.condition, settings)) return;

    item.effects.forEach(effect => {
      const amount = readNumber(effect.amounts?.[gradeIndex]);
      if (effect.kind === "damage") {
        addDamageGroup(damageGroups, effect.key, amount);
        return;
      }
      if (effect.kind === "flat") {
        addFlatBonus(flat, effect.key, amount);
        return;
      }
      if (effect.kind === "percent") {
        percentBonuses[effect.key] = readNumber(percentBonuses[effect.key]) + amount;
      }
    });
  });
}

function getBraceletGradeIndex(value) {
  return BRACELET_GRADES.findIndex(grade => grade.value === value);
}

function isDirectionalConditionActive(condition, settings) {
  if (!condition) return true;
  if (condition === "backAttack") return Boolean(settings?.backAttack);
  if (condition === "headAttack") return Boolean(settings?.headAttack);
  // 일격처럼 뒤든 머리든 방향성이기만 하면 되는 것. 백·헤드 중 하나면 붙는다.
  if (condition === "directional") return Boolean(settings?.backAttack) || Boolean(settings?.headAttack);
  if (condition === "nonDirectional") return !settings?.backAttack && !settings?.headAttack;
  return false;
}

function normalizeAccessories(accessories) {
  const nextRings = Array.isArray(accessories?.rings) ? accessories.rings : [];
  const nextEarrings = Array.isArray(accessories?.earrings) ? accessories.earrings : [];
  return {
    necklace: {
      ...DEFAULT_STATE.accessories.necklace,
      ...(accessories?.necklace || {}),
    },
    earrings: DEFAULT_STATE.accessories.earrings.map((earring, index) => ({
      ...earring,
      ...(nextEarrings[index] || {}),
    })),
    rings: DEFAULT_STATE.accessories.rings.map((ring, index) => ({
      ...ring,
      ...(nextRings[index] || {}),
    })),
  };
}

function calculateAccessoryBonuses(accessories) {
  const result = {
    additionalDamage: getAccessoryOptionValue("necklace", "additionalDamage", accessories.necklace.additionalDamage),
    // 목걸이의 '적에게 주는 피해'. 원한과 같은 그룹이라 서로 곱해진다.
    dealtDamage: getAccessoryOptionValue("necklace", "dealtDamage", accessories.necklace.dealtDamage),
    critRate: 0,
    critDamage: 0,
    attackPower: 0,
    weaponAttack: 0,
  };

  accessories.earrings.forEach(earring => {
    result.attackPower += getAccessoryOptionValue("earring", "attackPower", earring.attackPower);
    result.weaponAttack += getAccessoryOptionValue("earring", "weaponAttack", earring.weaponAttack);
  });
  accessories.rings.forEach(ring => {
    result.critRate += getAccessoryOptionValue("ring", "critRate", ring.critRate);
    result.critDamage += getAccessoryOptionValue("ring", "critDamage", ring.critDamage);
  });
  return result;
}

function getAccessoryOptionValue(part, field, grade) {
  return readNumber(ACCESSORY_OPTION_VALUES[part]?.[field]?.[grade]);
}

function normalizeAttack(attack) {
  return {
    weaponAttack: Math.max(0, readNumber(attack?.weaponAttack)),
    mainStat: Math.max(0, readNumber(attack?.mainStat)),
    flatAttack: Math.max(0, readNumber(attack?.flatAttack)),
    // 불러오기가 채우는 조각. 이걸 안 들고 다니면 세팅을 저장했다 열 때마다
    // 조립이 무너져 기준값이 0이 되고, 평면 증가가 통째로 안 세어진다.
    weaponFlat: Math.max(0, readNumber(attack?.weaponFlat)),
    weaponPercent: Math.max(0, readNumber(attack?.weaponPercent)),
    mainFlat: Math.max(0, readNumber(attack?.mainFlat)),
    mainTotal: Math.max(0, readNumber(attack?.mainTotal)),
    baseAttackPower: Math.max(0, readNumber(attack?.baseAttackPower)),
    baseScalePercent: Math.max(0, readNumber(attack?.baseScalePercent)),
    baseFlat: Math.max(0, readNumber(attack?.baseFlat)),
    weaponFlatAll: Math.max(0, readNumber(attack?.weaponFlatAll)),
    avatarPercent: Math.max(0, readNumber(attack?.avatarPercent)),
  };
}

function assembleAttack(inputState) {
  const source = inputState?.attack || {};
  const convenience = inputState?.convenience;
  const weaponFlat = Math.max(0, readNumber(source.weaponFlat));
  const mainFlat = Math.max(0, readNumber(source.mainFlat));
  const karma = Math.max(0, readNumber(convenience?.awakeningKarmaLevel)) * ARC_PASSIVE_CONSTANTS.awakeningKarmaWeaponPerLevel;
  const ranch = resolveRanchMainStat(inputState);

  const weaponAttack = weaponFlat > 0
    ? weaponFlat * (1 + (readNumber(source.weaponPercent) + karma) / 100)
    : Math.max(0, readNumber(source.weaponAttack));

  // 힘민지 총합은 되짚은 값이 이긴다.
  //
  // 장비만 더하면 물약·도감·원정대 몫(약 2,400)이 빠져 0.4% 모자란다. 게임이
  // 알려 준 기본 공격력에는 그게 이미 들어 있으므로, 되짚은 값이 있으면 그것을
  // 총합으로 못 박고 배수는 나누는 쪽으로만 쓴다 — 그래야 목장 등급을 잘못
  // 적어 두어도 총합은 게임과 맞고, 어긋나는 것은 평면을 나눌 기준뿐이다.
  const mainScale = 1 + (avatarTotal(source) + ranch) / 100;
  const derivedTotal = derivedMainTotal(inputState);
  const mainTotal = derivedTotal > 0 ? derivedTotal : Math.max(0, readNumber(source.mainTotal));
  const mainStat = mainTotal > 0
    ? mainTotal
    : (mainFlat > 0 ? mainFlat * mainScale : Math.max(0, readNumber(source.mainStat)));

  return {
    weaponAttack: Math.round(weaponAttack),
    mainStat: Math.round(mainStat),
    flatAttack: Math.max(0, readNumber(source.flatAttack)),
    // 순수 공격력을 기본 공격력으로 부풀리는 배수(보석 + 어빌리티 스톤).
    // 공격력 사슬이 읽는다 — 조립한 값과 같이 다녀야 흩어지지 않는다.
    baseScalePercent: Math.max(0, readNumber(source.baseScalePercent)),
    baseFlat: Math.max(0, readNumber(source.baseFlat)),
    // 사슬이 쓸 조각. 평면과 퍼센트를 갈라 둔다 — 게임 수식의 A·B가
    // (평면 합) × (1 + 퍼센트 합)이라 둘이 한 번만 만나야 하기 때문이다.
    karmaWeaponPercent: karma,
    mainScalePercent: avatarTotal(source) + ranch,
    // 평면 증가를 나눌 기준. 조립한 값이 아니라 **배수 이전**의 합이다.
    //
    //   지능 = (장비 598,677 + 채끝 12,000) × 1.09
    //   채끝의 몫 = (598,677 + 12,000)/598,677 = 1.02004   → 배수가 약분된다
    //
    // 게임에서 잰 값과 정확히 맞는다: 채끝을 먹으면 지능이 655,151 → 668,231,
    // 차이 13,080 = 12,000 × 1.09. 조립한 값(652,558)으로 나누면 1.839%가 나와
    // 채끝을 9% 낮게 본다 — 와인이냐 채끝이냐가 그 차이에서 갈린다.
    //
    // 팔찌 무공 +9,000도 같은 자리다. 그래서 weaponFlat은 팔찌를 안 담는다.
    weaponBase: weaponFlat > 0 ? weaponFlat : Math.max(0, readNumber(source.weaponAttack)),
    mainBase: mainTotal > 0
      ? mainTotal / mainScale
      : (mainFlat > 0 ? mainFlat : Math.max(0, readNumber(source.mainStat))),
  };
}

const SUPPORT_BUFF_BY_LEVEL = { 10: 21, 11: 21.2, 12: 21.5, 13: 21.7, 14: 22 };

function supportAttackPower(support, myBase) {
  if (!support || support.on === false) return 0;
  const typed = Math.max(0, readNumber(support.baseAttackPower));
  const base = typed > 0 ? typed : Math.max(0, readNumber(myBase));
  if (!(base > 0)) return 0;
  const level = clamp(Math.round(readNumber(support.skillLevel) || 14), 10, 14);
  const share = (SUPPORT_BUFF_BY_LEVEL[level] ?? 22) / 100;
  const boost = Math.max(0, readNumber(support.attackBoostPercent));
  return base * share * (1 + boost / 100);
}

function baseAttackPower(attack) {
  const { weaponAttack, mainStat } = normalizeAttack(attack);
  if (weaponAttack <= 0 || mainStat <= 0) return 0;
  return Math.sqrt(mainStat * weaponAttack / 6);
}

function emptyFlatBonuses() {
  return { weaponAttack: 0, mainStat: 0, attackPower: 0 };
}

function applyFlatAttackBonuses(flat, attack, damageGroups) {
  // 나누는 값은 배수 이전의 합이다 — assembleAttack의 weaponBase/mainBase 참고.
  // 조립한 값으로 나누면 아바타·목장·카르마만큼 평면 증가가 작아 보인다.
  const base = {
    weaponAttack: Math.max(0, readNumber(attack?.weaponBase ?? attack?.weaponAttack)),
    mainStat: Math.max(0, readNumber(attack?.mainBase ?? attack?.mainStat)),
  };
  const power = baseAttackPower(attack);
  const dropped = [];

  const convert = (amount, divisor, group, label) => {
    const value = readNumber(amount);
    if (value === 0) return;
    if (divisor <= 0) {
      dropped.push({ label, amount: value });
      return;
    }
    addDamageGroup(damageGroups, group, value / divisor * 100);
  };

  // 평면을 퍼센트로 바꾸던 자리였다. 지금은 공격력 사슬이 평면을 평면대로
  // 받으므로 환산이 필요 없다 — 오히려 틀렸다. 게임 수식의 A·B는
  // (평면 합) × (1 + 퍼센트 합)이라 둘이 한 번만 만나는데, 환산하면 팔찌
  // 무공 9,000이 제 몫의 퍼센트가 되어 연마 퍼센트와 한 번 더 곱해졌다.
  //
  // 기준값이 없어 못 세는 것만 여기서 걸러 알린다.
  if (readNumber(flat.weaponAttack) !== 0 && base.weaponAttack <= 0) {
    dropped.push({ label: "평면 무기 공격력", amount: readNumber(flat.weaponAttack) });
  }
  if (readNumber(flat.mainStat) !== 0 && base.mainStat <= 0) {
    dropped.push({ label: "평면 힘민지", amount: readNumber(flat.mainStat) });
  }
  if (readNumber(flat.attackPower) !== 0 && power <= 0) {
    dropped.push({ label: "평면 공격력", amount: readNumber(flat.attackPower) });
  }

  return dropped;
}

function addFlatBonus(flat, key, amount) {
  if (!flat || !Object.hasOwn(flat, key)) return;
  flat[key] = readNumber(flat[key]) + readNumber(amount);
}

const FOODS = [
  { id: "none", label: "안 먹음", summary: "" },
  { id: "wine", label: "베르닐 와인", summary: "이동 속도 +3%", moveSpeed: 3 },
  { id: "blessing", label: "에아달린의 축복", summary: "공격 속도 +3%", attackSpeed: 3 },
  { id: "skewer", label: "명인의 쫄깃한 꼬치구이", summary: "힘·민첩·지능 +3,000", mainStat: 3000 },
  { id: "steak", label: "거장의 채끝 스테이크", summary: "힘·민첩·지능 +12,000", mainStat: 12000 },
];

const FOOD_BY_ID = new Map(FOODS.map(food => [food.id, food]));

function getFood(id) {
  return FOOD_BY_ID.get(String(id ?? "none")) ?? FOOD_BY_ID.get("none");
}

function applyFoodEffects(id, percentBonuses, flatBonuses) {
  const food = getFood(id);
  if (food.attackSpeed) percentBonuses.attackSpeedOnly = readNumber(percentBonuses.attackSpeedOnly) + food.attackSpeed;
  if (food.moveSpeed) percentBonuses.moveSpeedOnly = readNumber(percentBonuses.moveSpeedOnly) + food.moveSpeed;
  if (food.mainStat) addFlatBonus(flatBonuses, "mainStat", food.mainStat);
  return food;
}

const RANCH_GRADES = [
  { value: 0, label: "없음", amount: 0 },
  { value: 0.4, label: "0.4%", amount: 0.4 },
  { value: 0.7, label: "0.7%", amount: 0.7 },
  { value: 1, label: "1%", amount: 1 },
];

function ranchAmount(grade) {
  if (grade === true) return 1;
  const value = readNumber(grade);
  const hit = RANCH_GRADES.find(item => item.value === value);
  return hit ? hit.amount : 0;
}

const PASSION_DANCE_GRADES = [
  { value: 0, label: "없음", amount: 0 },
  { value: 1, label: "1Lv", amount: 6 },
  { value: 2, label: "2Lv", amount: 12 },
];

function passionDanceAmount(level) {
  const hit = PASSION_DANCE_GRADES.find(item => item.value === Math.round(readNumber(level)));
  return hit ? hit.amount : 0;
}

const AVATAR_SLOTS = [
  { key: "weapon", label: "무기" },
  { key: "head", label: "머리" },
  { key: "top", label: "상의" },
  { key: "bottom", label: "하의" },
];

const AVATAR_GRADES = [
  { value: "none", label: "없음", amount: 0 },
  { value: "epic", label: "영웅", amount: 1 },
  { value: "legendary", label: "전설", amount: 2 },
];

function avatarAmount(grade) {
  const hit = AVATAR_GRADES.find(item => item.value === grade);
  return hit ? hit.amount : 0;
}

function avatarTotal(attack) {
  const slots = attack?.avatars;
  if (slots && typeof slots === "object") {
    return AVATAR_SLOTS.reduce((sum, slot) => sum + avatarAmount(slots[slot.key]), 0);
  }
  return Math.max(0, readNumber(attack?.avatarPercent));
}

function derivedMainTotal(inputState) {
  const source = inputState?.attack || {};
  const karma = Math.max(0, readNumber(inputState?.convenience?.awakeningKarmaLevel))
    * ARC_PASSIVE_CONSTANTS.awakeningKarmaWeaponPerLevel;
  const gameBase = Math.max(0, readNumber(source.baseAttackPower));
  const baseScale = 1 + Math.max(0, readNumber(source.baseScalePercent)) / 100;
  const weaponAll = Math.max(0, readNumber(source.weaponFlatAll));
  if (!(gameBase > 0) || !(weaponAll > 0)) return 0;
  // D = (C + 평면) x 배수 를 뒤집는다. 평면을 안 빼면 C가 850만큼 커지고,
  // 제곱으로 들어가므로 힘민지가 1% 부풀어 나온다.
  const pure = gameBase / baseScale - Math.max(0, readNumber(source.baseFlat));
  if (!(pure > 0)) return 0;
  return 6 * pure ** 2 / (weaponAll * (1 + (readNumber(source.weaponPercent) + karma) / 100));
}

function ranchResidual(inputState) {
  const source = inputState?.attack || {};
  const mainFlat = Math.max(0, readNumber(source.mainFlat));
  const outside = Math.max(0, readNumber(inputState?.collection?.expeditionMainStat));
  const total = derivedMainTotal(inputState);
  if (!(total > 0) || !(mainFlat > 0)) return null;
  return (total / (mainFlat + outside) - 1) * 100 - avatarTotal(source);
}

function outsideMainStat(inputState) {
  const source = inputState?.attack || {};
  const mainFlat = Math.max(0, readNumber(source.mainFlat));
  const total = derivedMainTotal(inputState);
  if (!(total > 0) || !(mainFlat > 0)) return null;
  const scale = 1 + (avatarTotal(source) + resolveRanchMainStat(inputState)) / 100;
  return total / scale - mainFlat;
}

function autoRanchAmount(inputState) {
  const residual = ranchResidual(inputState);
  if (residual === null) return 0;
  return RANCH_GRADES.reduce(
    (best, grade) => (Math.abs(grade.amount - residual) < Math.abs(best - residual) ? grade.amount : best),
    0,
  );
}

function resolveRanchMainStat(inputState) {
  const source = inputState?.collection ?? {};
  // 둘로 나뉘기 전 저장본은 ranch 한 칸에 둘 다 들어 있었다.
  const grade = source.ranchMainStat ?? source.ranch;
  return grade === "auto" ? autoRanchAmount(inputState) : ranchAmount(grade);
}

function resolveRanchDamage(collection) {
  return ranchAmount(collection?.ranchDamage ?? collection?.ranch);
}

function applyAwakeningEffects(awakening, percentBonuses, damageGroups, conversions) {
  const result = awakeningBonuses(awakening?.job, awakening?.nodeLevels, awakening?.uptime);
  // 식으로 붙는 것은 여기서 값을 못 낸다 — 재료가 되는 속도·치적이 아직 없다.
  // 직접 입력 효과와 같은 줄에 실어 두면 계산이 제 단계에서 푼다.
  if (Array.isArray(conversions)) conversions.push(...(result.conversions ?? []));
  Object.entries(result.percentBonuses).forEach(([key, amount]) => {
    percentBonuses[key] = readNumber(percentBonuses[key]) + readNumber(amount);
  });
  Object.entries(result.damageGroups).forEach(([key, amount]) => {
    addDamageGroup(damageGroups, key, amount);
  });
  return result;
}

function applySynergyEffects(inputState, percentBonuses, damageGroups) {
  const result = synergyBonuses(inputState.awakening, inputState.synergy, inputState.settings);
  Object.entries(result.damageGroups).forEach(([key, amount]) => addDamageGroup(damageGroups, key, amount));
  Object.entries(result.percentBonuses).forEach(([key, amount]) => {
    percentBonuses[key] = readNumber(percentBonuses[key]) + readNumber(amount);
  });
  if (result.critOnly !== 0) addCritOnlyDamage(percentBonuses, result.critOnly);
  return result;
}

function addDamageGroup(damageGroups, key, amount) {
  const value = readNumber(amount);
  if (value === 0) return;

  if (MULTIPLICATIVE_DAMAGE_GROUPS.has(key)) {
    const currentMultiplier = 1 + readNumber(damageGroups[key]) / 100;
    const nextMultiplier = currentMultiplier * (1 + value / 100);
    damageGroups[key] = (nextMultiplier - 1) * 100;
    return;
  }

  damageGroups[key] = readNumber(damageGroups[key]) + value;
}

function calculateBluntThornBonus(level, critRateRaw) {
  if (level <= 0) {
    return { damage: 0, convertedCrit: 0, excessCrit: 0, rate: 0, limit: 0, raw: 0, capped: false };
  }
  const excessCritRate = Math.max(0, readNumber(critRateRaw) - 80);
  const conversionRate = level >= 2 ? 1.5 : 1.25;
  const conversionLimit = level >= 2 ? 60 : 45;
  const raw = excessCritRate * conversionRate;
  return {
    damage: Math.min(raw, conversionLimit),
    convertedCrit: Math.min(excessCritRate, conversionLimit / conversionRate),
    // 상한 80%를 넘긴 치적. 전환의 재료다.
    excessCrit: excessCritRate,
    rate: conversionRate,
    limit: conversionLimit,
    raw,
    capped: raw > conversionLimit,
  };
}

function calculateSonicBreakthroughBonus(level, attackSpeedBonus, moveSpeedBonus) {
  if (level <= 0) {
    return {
      damage: 0, baseDamage: 0, capBonus: 0, excessDamage: 0,
      baseRate: 0, excessRate: 0, fixedCapBonus: 0, maxDamage: 0,
      speedSum: 0, excessSum: 0, bothOverCap: false, capped: false,
    };
  }

  const maxDamage = level >= 2 ? 24 : 12;
  const baseRate = level >= 2 ? 0.1 : 0.05;
  const fixedCapBonus = level >= 2 ? 8 : 4;
  const excessRate = level >= 2 ? 0.3 : 0.15;
  const appliedAttackBonus = clamp(readNumber(attackSpeedBonus), 0, 40);
  const appliedMoveBonus = clamp(readNumber(moveSpeedBonus), 0, 40);
  const attackExcess = Math.max(0, readNumber(attackSpeedBonus) - 40);
  const moveExcess = Math.max(0, readNumber(moveSpeedBonus) - 40);
  const bothOverCap = attackExcess > 0 && moveExcess > 0;
  const baseDamage = (appliedAttackBonus + appliedMoveBonus) * baseRate;
  const capBonus = bothOverCap ? fixedCapBonus : 0;
  const rawExcessDamage = bothOverCap ? (attackExcess + moveExcess) * excessRate : 0;
  const excessDamage = Math.min(rawExcessDamage, Math.max(0, maxDamage - baseDamage - capBonus));

  return {
    damage: baseDamage + capBonus + excessDamage,
    baseDamage,
    capBonus,
    excessDamage,
    // 계기판이 그대로 옮겨 적을 근거들
    baseRate,
    excessRate,
    fixedCapBonus,
    maxDamage,
    speedSum: appliedAttackBonus + appliedMoveBonus,
    excessSum: attackExcess + moveExcess,
    bothOverCap,
    capped: rawExcessDamage > excessDamage,
  };
}

const COOLDOWN_GROUP_KEYS = ["swift", "generic", "mana", "skill", "jewel"];

const COOLDOWN_GROUP_LABELS = {
  swift: "신속",
  generic: "직접 입력",
  mana: "끝마/무마",
  skill: "최훈/타지",
  jewel: "보석",
};

const JEWEL_MAX_LEVEL = 10;

function jewelCooldown(level) {
  const value = clamp(Math.round(readNumber(level)), 0, JEWEL_MAX_LEVEL);
  return value <= 0 ? 0 : (value + 2) * 2;
}

function getCooldownGroupLabel(groups) {
  const labels = COOLDOWN_GROUP_KEYS
    .filter(key => readNumber(groups[key]) !== 0)
    .map(key => COOLDOWN_GROUP_LABELS[key]);
  return labels.length > 0 ? labels.join(" × ") : "없음";
}

function getNodeCost(node) {
  return node.cost || EVOLUTION_TIERS[node.tier]?.cost || 0;
}

function normalizeNodeLevels(nodeLevels) {
  return NODE_LIBRARY.reduce((levels, node) => {
    levels[node.id] = clamp(Math.round(readNumber(nodeLevels?.[node.id])), 0, node.maxLevel);
    return levels;
  }, {});
}

function emptyNodeLevels() {
  return NODE_LIBRARY.reduce((levels, node) => {
    levels[node.id] = 0;
    return levels;
  }, {});
}

function mergeState(base, next) {
  // 치적/치피는 출처별 입력으로 갈렸다. 예전 저장본에 남아 있어도 무시한다.
  const nextBase = { ...(next.base || {}) };
  delete nextBase.baseCritDamage;
  delete nextBase.baseCritRate;
  delete nextBase.critDamageBonus;

  const accessories = normalizeAccessories(next.accessories);
  const bracelet = normalizeBracelet(next.bracelet);

  return {
    base: { ...base.base, ...nextBase },
    settings: { ...base.settings, ...(next.settings || {}) },
    convenience: { ...base.convenience, ...(next.convenience || {}) },
    accessories,
    bracelet,
    attack: normalizeAttack(next.attack),
    awakening: {
      job: readNumber(next.awakening?.job),
      nodeLevels: { ...(next.awakening?.nodeLevels || {}) },
      uptime: { ...(next.awakening?.uptime || {}) },
    },
    // 적어 넣은 줄만 담는다. 내 줄은 직업과 깨달음이 정하므로 가동율만 저장한다.
    synergy: normalizeSynergy(next.synergy),
    arkGrid: normalizeArkGrid(next.arkGrid),
    collection: { ...base.collection, ...(next.collection || {}) },
    weapon: { ...base.weapon, ...(next.weapon || {}) },
    jewel: { ...base.jewel, ...(next.jewel || {}) },
    engravings: { ...(next.engravings || {}) },
    engravingStones: { ...(next.engravingStones || {}) },
    nodeLevels: { ...(next.nodeLevels || {}) },
    baseEffects: normalizeBaseEffects(next.baseEffects, base.baseEffects),
    specBundles: normalizeSpecBundles(next.specBundles),
    selectedTier: next.selectedTier || base.selectedTier,
    setupName: next.setupName || "",
  };
}

function normalizeBaseEffects(effects, fallbackEffects) {
  const source = Array.isArray(effects) ? effects : cloneState(fallbackEffects);

  return source.flatMap(effect => {
    if (effect.category !== "attackSpeed") return [effect];

    const id = effect.id || makeId();
    const label = String(effect.label || "공격/이동속도").trim();
    const genericLabel = /공격\s*\/?\s*이동속도|공이속/.test(label);
    return [
      {
        ...effect,
        id,
        label: genericLabel ? "공격속도" : `${label} · 공속`,
        category: "attackSpeedOnly",
      },
      {
        ...effect,
        id: `${id}-move`,
        label: genericLabel ? "이동속도" : `${label} · 이속`,
        category: "moveSpeedOnly",
      },
    ];
  });
}

export {
  DEFAULT_STATE,
  MULTIPLICATIVE_DAMAGE_GROUPS,
  SQRT_DAMAGE_GROUPS,
  ATTACK_CHAIN_GROUPS,
  damageGroupFactor,
  normalizeSynergy,
  legacySynergyRows,
  STAGGER_DAMAGE_GROUPS,
  getStaggerShare,
  normalizeArkGrid,
  applyCoreEffect,
  applyArkGridEffects,
  applyCollectionEffects,
  applyWeaponEffects,
  DAMAGE_MIX_KEYS,
  DAMAGE_MIX_LABELS,
  normalizeDamageMix,
  SPEC_BUNDLE_KINDS,
  normalizeSpecBundles,
  specBundleValue,
  specBundleRowFactor,
  specBundleVariables,
  specBundleBlend,
  getManaShareRatio,
  getManaCooldownShareRatio,
  blendCooldownRemain,
  calculateMetrics,
  finalizeMetrics,
  addCritOnlyDamage,
  applyEffect,
  applyBaseEffect,
  effectUptimeRate,
  FORMULA_VARIABLES,
  getFormulaStage,
  evaluateFormula,
  buildFormulaVariables,
  applyFormulaEffects,
  applyEngravingEffects,
  applyEngravingTier,
  getEngravingTierIndex,
  normalizeBracelet,
  applyBraceletEffects,
  getBraceletGradeIndex,
  isDirectionalConditionActive,
  normalizeAccessories,
  calculateAccessoryBonuses,
  getAccessoryOptionValue,
  normalizeAttack,
  assembleAttack,
  SUPPORT_BUFF_BY_LEVEL,
  supportAttackPower,
  baseAttackPower,
  emptyFlatBonuses,
  applyFlatAttackBonuses,
  addFlatBonus,
  FOODS,
  FOOD_BY_ID,
  getFood,
  applyFoodEffects,
  RANCH_GRADES,
  ranchAmount,
  PASSION_DANCE_GRADES,
  passionDanceAmount,
  AVATAR_SLOTS,
  AVATAR_GRADES,
  avatarAmount,
  avatarTotal,
  derivedMainTotal,
  ranchResidual,
  outsideMainStat,
  autoRanchAmount,
  resolveRanchMainStat,
  resolveRanchDamage,
  applyAwakeningEffects,
  applySynergyEffects,
  addDamageGroup,
  calculateBluntThornBonus,
  calculateSonicBreakthroughBonus,
  COOLDOWN_GROUP_KEYS,
  COOLDOWN_GROUP_LABELS,
  JEWEL_MAX_LEVEL,
  jewelCooldown,
  getCooldownGroupLabel,
  getNodeCost,
  normalizeNodeLevels,
  emptyNodeLevels,
  mergeState,
  normalizeBaseEffects,
};
