// GENERATED by scripts/extract-core.mjs — do not edit by hand.
// Source: ../../../../legacy/optimizer.js (search engine, UI stripped)

import { EVOLUTION_TIERS, NODE_LIBRARY, ARC_PASSIVE_CONSTANTS } from "./data.js";
import { ENGRAVING_TIERS, ENGRAVING_LIBRARY, NON_RAID_ENGRAVINGS } from "./engravings.js";
import { readNumber, clamp } from "./util.js";
import {
  DEFAULT_STATE, finalizeMetrics, applyBaseEffect, applyBraceletEffects, applyEngravingTier,
  calculateAccessoryBonuses, normalizeAccessories, normalizeBracelet, addDamageGroup,
  getEngravingTierIndex, getManaShareRatio, getNodeCost, emptyNodeLevels,
} from "./metrics.js";

const OPTIMIZER_EXHAUSTIVE_LIMIT = 5000000;

const OPTIMIZER_CHUNK_MS = 28;

const OPTIMIZER_CLOCK_INTERVAL = 2000;

const OPTIMIZER_REFINE_ROUNDS = 3;

const OPTIMIZER_REFINE_SEEDS = 24;

const OPTIMIZER_MAX_EXPANSIONS = 800000;

const OPTIMIZER_REFINE_BUDGET = 800000;

const OPTIMIZER_PET_OPTIONS = ["none", "critStat", "specStat", "swiftStat"];

const OPTIMIZER_PET_LABELS = {
  none: "펫 없음",
  critStat: "펫 치명",
  specStat: "펫 특화",
  swiftStat: "펫 신속",
};

const OPTIMIZER_TIER1_STEPS = { step10: 10, step5: 5, step2: 2 };

const OPTIMIZER_ENGRAVING_ROLES = ["locked", "candidate", "excluded"];

const OPTIMIZER_ROLE_LABELS = { locked: "고정", candidate: "후보", excluded: "제외" };

const DIRECTION_REQUIREMENT_LABELS = {
  backAttack: "백어택을 켜야 적용",
  headAttack: "헤드어택을 켜야 적용",
  nonDirectional: "백어택·헤드어택을 모두 꺼야 적용",
};

function getModeledStatKeys(sourceState) {
  const keys = new Set(["critStat", "swiftStat"]);
  if (readNumber(sourceState.base.specDamagePer100) !== 0) keys.add("specStat");
  return keys;
}

function isNodeImpactful(node, modeledStatKeys) {
  return node.effects.some(effect => {
    if (effect.kind === "note") return false;
    if (effect.kind === "stat") return modeledStatKeys.has(effect.key);
    return true;
  });
}

function enumerateNodeCombos(nodes, cost, maxPoints, step) {
  const combos = [];
  const levels = new Array(nodes.length).fill(0);

  const walk = (index, used) => {
    if (index === nodes.length) {
      const picked = [];
      let goddessLevel = 0;
      for (let i = 0; i < nodes.length; i += 1) {
        if (levels[i] <= 0) continue;
        picked.push([nodes[i].id, levels[i]]);
        if (nodes[i].id === "e2-goddess-blessing") goddessLevel = levels[i];
      }
      combos.push({ kind: "nodes", levels: picked, points: used, goddessLevel });
      return;
    }

    const node = nodes[index];
    const affordable = Math.min(node.maxLevel, Math.floor((maxPoints - used) / cost));
    for (let level = 0; level <= affordable; level += step) {
      levels[index] = level;
      walk(index + 1, used + level * cost);
    }
    levels[index] = 0;
  };

  walk(0, 0);
  return combos;
}

function keepFullBudgetCombos(combos) {
  const best = combos.reduce((max, combo) => Math.max(max, combo.points), 0);
  const filtered = combos.filter(combo => combo.points === best);
  return filtered.length > 0 ? filtered : combos;
}

function getModeledEngravings() {
  return ENGRAVING_LIBRARY.filter(item => item.effects.length > 0);
}

function defaultEngravingRole(item) {
  return NON_RAID_ENGRAVINGS.has(item.id) ? "excluded" : "candidate";
}

function enumerateEngravingSets(candidates, pickCount, locked) {
  const options = [];
  const chosen = [];

  const walk = index => {
    if (chosen.length === pickCount) {
      options.push({ kind: "engravingSet", active: locked.concat(chosen) });
      return;
    }
    if (index >= candidates.length) return;
    if (candidates.length - index < pickCount - chosen.length) return;

    chosen.push(candidates[index]);
    walk(index + 1);
    chosen.pop();
    walk(index + 1);
  };

  walk(0);
  return options;
}

function createTopList(limit, key) {
  const items = [];
  const seen = new Set();
  let threshold = -Infinity;

  return {
    items,
    get threshold() {
      return items.length >= limit ? threshold : -Infinity;
    },
    offer(entry) {
      const score = entry[key];
      if (items.length >= limit && score <= threshold) return;
      if (seen.has(entry.signature)) return;
      seen.add(entry.signature);
      items.push(entry);
      items.sort((a, b) => b[key] - a[key]);
      if (items.length > limit) {
        const dropped = items.pop();
        seen.delete(dropped.signature);
      }
      threshold = items[items.length - 1][key];
    },
  };
}

function createParetoFront() {
  const items = [];

  // Largest index whose damageIndex beats `value`, or -1 when none does.
  // `strict` distinguishes "> value" (insert position) from ">= value"
  // (domination test); equal-damage entries must be handled differently by each.
  const floorIndex = (damageIndex, strict) => {
    let low = 0;
    let high = items.length - 1;
    let found = -1;
    while (low <= high) {
      const mid = (low + high) >> 1;
      const beats = strict ? items[mid].damageIndex > damageIndex : items[mid].damageIndex >= damageIndex;
      if (beats) {
        found = mid;
        low = mid + 1;
      } else {
        high = mid - 1;
      }
    }
    return found;
  };

  return {
    items,
    // Cheap rejection so a dominated point never allocates a snapshot. dpsIndex
    // ascends with index, so the last entry at or above this damage is the
    // strongest possible dominator.
    accepts(damageIndex, dpsIndex) {
      const floor = floorIndex(damageIndex, false);
      return floor < 0 || items[floor].dpsIndex < dpsIndex;
    },
    offer(entry) {
      const floor = floorIndex(entry.damageIndex, false);
      if (floor >= 0 && items[floor].dpsIndex >= entry.dpsIndex) return;

      // Everything from here on has damage <= the new entry, so the leading run
      // with dps <= the new entry is now dominated and drops out.
      const insertAt = floorIndex(entry.damageIndex, true) + 1;
      let removeCount = 0;
      while (insertAt + removeCount < items.length && items[insertAt + removeCount].dpsIndex <= entry.dpsIndex) {
        removeCount += 1;
      }
      items.splice(insertAt, removeCount, entry);
    },
  };
}

function annotateParetoKnees(front) {
  const rates = front.map((item, index) => {
    if (index === 0) return 0;
    const previous = front[index - 1];
    const damageDrop = previous.damageIndex - item.damageIndex;
    if (damageDrop <= 0) return 0;
    return (item.dpsIndex - previous.dpsIndex) / damageDrop;
  });

  const scored = rates.filter((rate, index) => index > 0 && rate > 0);
  const median = scored.length > 0
    ? scored.slice().sort((a, b) => a - b)[Math.floor(scored.length / 2)]
    : 0;

  return front.map((item, index) => ({
    ...item,
    exchangeRate: rates[index],
    // Flagged when this step trades markedly better than the front's norm.
    isKnee: index > 0 && median > 0 && rates[index] >= median * 1.6,
  }));
}

function createChunkClock() {
  let deadline = performance.now() + OPTIMIZER_CHUNK_MS;
  let sinceCheck = 0;

  return {
    // True once the current chunk has used its time budget.
    expired() {
      sinceCheck += 1;
      if (sinceCheck < OPTIMIZER_CLOCK_INTERVAL) return false;
      sinceCheck = 0;
      return performance.now() >= deadline;
    },
    reset() {
      sinceCheck = 0;
      deadline = performance.now() + OPTIMIZER_CHUNK_MS;
    },
  };
}

function selectBeam(candidates, beamWidth) {
  const half = Math.max(1, Math.floor(beamWidth / 2));
  const byDamage = candidates.slice().sort((a, b) => b.damageIndex - a.damageIndex).slice(0, half);
  const byDps = candidates.slice().sort((a, b) => b.dpsIndex - a.dpsIndex).slice(0, half);
  const merged = [];
  const seen = new Set();

  [...byDamage, ...byDps].forEach(item => {
    const key = item.indexes.join(",");
    if (seen.has(key)) return;
    seen.add(key);
    merged.push(item);
  });

  return merged;
}

export {
  OPTIMIZER_EXHAUSTIVE_LIMIT,
  OPTIMIZER_CHUNK_MS,
  OPTIMIZER_CLOCK_INTERVAL,
  OPTIMIZER_REFINE_ROUNDS,
  OPTIMIZER_REFINE_SEEDS,
  OPTIMIZER_MAX_EXPANSIONS,
  OPTIMIZER_REFINE_BUDGET,
  OPTIMIZER_PET_OPTIONS,
  OPTIMIZER_PET_LABELS,
  OPTIMIZER_TIER1_STEPS,
  OPTIMIZER_ENGRAVING_ROLES,
  OPTIMIZER_ROLE_LABELS,
  DIRECTION_REQUIREMENT_LABELS,
  getModeledStatKeys,
  isNodeImpactful,
  enumerateNodeCombos,
  keepFullBudgetCombos,
  getModeledEngravings,
  defaultEngravingRole,
  enumerateEngravingSets,
  createTopList,
  createParetoFront,
  annotateParetoKnees,
  createChunkClock,
  selectBeam,
};
