// GENERATED by scripts/extract-core.mjs - do not edit by hand.
// Source: ../../../../legacy/optimizer.js (search engine, UI stripped)

import { EVOLUTION_TIERS, NODE_LIBRARY, ARC_PASSIVE_CONSTANTS } from "./data.js";
import { ENGRAVING_TIERS, ENGRAVING_LIBRARY } from "./engravings.js";
import { readNumber, clamp } from "./util.js";
import {
  DEFAULT_STATE, finalizeMetrics, applyBaseEffect, applyBraceletEffects, applyEngravingTier,
  calculateAccessoryBonuses, normalizeAccessories, normalizeBracelet, addDamageGroup,
  getEngravingTierIndex, getManaShareRatio, getNodeCost, emptyNodeLevels,
  FOODS, assembleAttack,
} from "./metrics.js";

const OPTIMIZER_EXHAUSTIVE_LIMIT = 5000000;

const OPTIMIZER_CHUNK_MS = 28;

const OPTIMIZER_CLOCK_INTERVAL = 2000;

const OPTIMIZER_REFINE_ROUNDS = 3;

const OPTIMIZER_REFINE_SEEDS = 24;

const OPTIMIZER_MAX_EXPANSIONS = 800000;

const OPTIMIZER_REFINE_BUDGET = 800000;

const OPTIMIZER_PET_OPTIONS = ["none", "critStat", "specStat", "swiftStat", "dominationStat"];

const OPTIMIZER_PET_LABELS = {
  none: "펫 없음",
  critStat: "펫 치명",
  specStat: "펫 특화",
  swiftStat: "펫 신속",
  // 제압은 대난투 비중을 적었을 때만 딜이 된다. 그래도 갈래로 둔다 —
  // 비중이 있는 사람에게는 실제로 고르는 선택지다.
  dominationStat: "펫 제압",
};

const OPTIMIZER_TIER1_STEPS = { step10: 10, step5: 5, step2: 2, step1: 1 };

const OPTIMIZER_ENGRAVING_ROLES = ["locked", "candidate", "excluded"];

const OPTIMIZER_ROLE_LABELS = { locked: "고정", candidate: "후보", excluded: "제외" };

const DIRECTION_REQUIREMENT_LABELS = {
  backAttack: "백어택을 켜야 적용",
  headAttack: "헤드어택을 켜야 적용",
  nonDirectional: "백어택·헤드어택을 모두 꺼야 적용",
};

const OPTIMIZER_INERT_NODES = new Map([
  ["e2-goddess-blessing", "서폿용 노드 — 딜러에게는 가치가 없다"],
  ["e3-passionate-dance", "서폿용 노드 — 딜러에게는 가치가 없다"],
]);

function getModeledStatKeys(sourceState) {
  const keys = new Set(["critStat", "swiftStat"]);
  if (readNumber(sourceState.base.specDamagePer100) !== 0) keys.add("specStat");
  // 특화 묶음이 있으면 특화가 실제 딜이 된다 — 후보에 올려야 저울질이 된다.
  if ((sourceState.specBundles || []).some(bundle =>
    readNumber(bundle?.share) > 0 && (bundle?.rows || []).length > 0)) {
    keys.add("specStat");
  }
  // 제압은 언제나 후보다.
  //
  // 예전에는 대난투 딜 비중을 적었을 때만 넣었다. 비중이 0이면 제압이 한 방
  // 딜에 아무 값도 안 내니 탐색이 헛돈다고 봤기 때문이다. 그런데 지금은 무력화
  // 가중 100%로 재는 대난투 순위가 따로 있다. 제압을 후보에서 빼면 그 순위가
  // 제압을 안 찍은 것들 중 1위가 된다 — 물어본 것과 다른 답이다.
  keys.add("dominationStat");
  return keys;
}

function isNodeImpactful(node, modeledStatKeys, excluded) {
  if (excluded && excluded.has(node.id)) return false;
  if (OPTIMIZER_INERT_NODES.has(node.id)) return false;
  return node.effects.some(effect => {
    if (effect.kind === "note") return false;
    if (effect.kind === "stat") return modeledStatKeys.has(effect.key);
    return true;
  });
}

function enumerateNodeCombos(nodes, cost, maxPoints, step) {
  const combos = [];
  const levels = new Array(nodes.length).fill(0);

  const walk = (index, used) => {
    if (index === nodes.length) {
      const picked = [];
      let goddessLevel = 0;
      for (let i = 0; i < nodes.length; i += 1) {
        if (levels[i] <= 0) continue;
        picked.push([nodes[i].id, levels[i]]);
        if (nodes[i].id === "e2-goddess-blessing") goddessLevel = levels[i];
      }
      combos.push({ kind: "nodes", levels: picked, points: used, goddessLevel });
      return;
    }

    const node = nodes[index];
    const affordable = Math.min(node.maxLevel, Math.floor((maxPoints - used) / cost));
    for (let level = 0; level <= affordable; level += step) {
      levels[index] = level;
      walk(index + 1, used + level * cost);
    }
    levels[index] = 0;
  };

  walk(0, 0);
  return combos;
}

function keepFullBudgetCombos(combos) {
  const best = combos.reduce((max, combo) => Math.max(max, combo.points), 0);
  const filtered = combos.filter(combo => combo.points === best);
  return filtered.length > 0 ? filtered : combos;
}

function getModeledEngravings() {
  return ENGRAVING_LIBRARY.filter(item => item.effects.length > 0);
}

const DEFAULT_CANDIDATES = new Set(["grudge", "cursed-doll"]);

function defaultEngravingRole(item) {
  return DEFAULT_CANDIDATES.has(item.id) ? "candidate" : "excluded";
}

function enumerateEngravingSets(candidates, pickCount, locked) {
  const options = [];
  const chosen = [];

  const walk = index => {
    if (chosen.length === pickCount) {
      options.push({ kind: "engravingSet", active: locked.concat(chosen) });
      return;
    }
    if (index >= candidates.length) return;
    if (candidates.length - index < pickCount - chosen.length) return;

    chosen.push(candidates[index]);
    walk(index + 1);
    chosen.pop();
    walk(index + 1);
  };

  walk(0);
  return options;
}

function createTopList(limit, key, tiebreak) {
  const items = [];
  const seen = new Set();
  const compare = (a, b) => (b[key] - a[key]) || (tiebreak ? b[tiebreak] - a[tiebreak] : 0);
  const edge = () => (items.length >= limit ? items[items.length - 1] : null);

  const wants = (score, tie) => {
    const last = edge();
    if (!last) return true;
    if (score > last[key]) return true;
    if (score < last[key]) return false;
    // 값이 같으면 tiebreak으로 가른다. tiebreak이 없으면 예전처럼 안 받는다.
    return tiebreak ? tie > last[tiebreak] : false;
  };

  return {
    items,
    wants,
    get threshold() {
      const last = edge();
      return last ? last[key] : -Infinity;
    },
    offer(entry) {
      if (!wants(entry[key], tiebreak ? entry[tiebreak] : 0)) return;
      if (seen.has(entry.signature)) return;
      seen.add(entry.signature);
      items.push(entry);
      items.sort(compare);
      if (items.length > limit) {
        const dropped = items.pop();
        seen.delete(dropped.signature);
      }
    },
  };
}

function createParetoFront(xKey, yKey) {
  const x = xKey || "damageIndex";
  const y = yKey || "dpsIndex";
  const items = [];

  // Largest index whose x beats `value`, or -1 when none does.
  // `strict` distinguishes "> value" (insert position) from ">= value"
  // (domination test); equal-x entries must be handled differently by each.
  const floorIndex = (damageIndex, strict) => {
    let low = 0;
    let high = items.length - 1;
    let found = -1;
    while (low <= high) {
      const mid = (low + high) >> 1;
      const beats = strict ? items[mid][x] > damageIndex : items[mid][x] >= damageIndex;
      if (beats) {
        found = mid;
        low = mid + 1;
      } else {
        high = mid - 1;
      }
    }
    return found;
  };

  return {
    items,
    // Cheap rejection so a dominated point never allocates a snapshot. dpsIndex
    // ascends with index, so the last entry at or above this damage is the
    // strongest possible dominator.
    accepts(damageIndex, dpsIndex) {
      const floor = floorIndex(damageIndex, false);
      return floor < 0 || items[floor][y] < dpsIndex;
    },
    offer(entry) {
      const floor = floorIndex(entry[x], false);
      if (floor >= 0 && items[floor][y] >= entry[y]) return;

      // Everything from here on has x <= the new entry, so the leading run
      // with y <= the new entry is now dominated and drops out.
      const insertAt = floorIndex(entry[x], true) + 1;
      let removeCount = 0;
      while (insertAt + removeCount < items.length && items[insertAt + removeCount][y] <= entry[y]) {
        removeCount += 1;
      }
      items.splice(insertAt, removeCount, entry);
    },
  };
}

function createChunkClock() {
  let deadline = performance.now() + OPTIMIZER_CHUNK_MS;
  let sinceCheck = 0;

  return {
    // True once the current chunk has used its time budget.
    expired() {
      sinceCheck += 1;
      if (sinceCheck < OPTIMIZER_CLOCK_INTERVAL) return false;
      sinceCheck = 0;
      return performance.now() >= deadline;
    },
    reset() {
      sinceCheck = 0;
      deadline = performance.now() + OPTIMIZER_CHUNK_MS;
    },
  };
}

const BEAM_METRICS = ["damageIndex", "dpsIndex", "staggerIndex"];

function selectBeam(candidates, beamWidth, metrics = BEAM_METRICS) {
  const keys = metrics.length > 0 ? metrics : BEAM_METRICS;
  const share = Math.max(1, Math.floor(beamWidth / keys.length));
  // 하한 조건이 걸린 탐색에서는 조건을 채운 후보가 먼저다. 빔은 앞 차원에서
  // 자른 것을 뒤에서 되돌리지 못하므로, 여기서 지표만 보고 고르면 마지막에
  // 조건을 통과하는 빌드가 하나도 안 남는 일이 생긴다. 채운 후보가 빔을 다
  // 채우지 못할 때만 모자란 순으로 나머지를 메운다.
  //
  // shortfall이 없으면(하한을 안 걸었으면) 전부 통과로 읽혀 예전과 같다.
  const ok = candidates.filter(item => !(item.shortfall > 0));
  const short = ok.length === candidates.length
    ? []
    : candidates.filter(item => item.shortfall > 0).sort((a, b) => a.shortfall - b.shortfall);

  const take = key => {
    const best = ok.slice().sort((a, b) => b[key] - a[key]).slice(0, share);
    return best.length >= share ? best : best.concat(short.slice(0, share - best.length));
  };

  const merged = [];
  const seen = new Set();

  keys.flatMap(key => take(key)).forEach(item => {
    const key = item.indexes.join(",");
    if (seen.has(key)) return;
    seen.add(key);
    merged.push(item);
  });

  return merged;
}

export {
  OPTIMIZER_EXHAUSTIVE_LIMIT,
  OPTIMIZER_CHUNK_MS,
  OPTIMIZER_CLOCK_INTERVAL,
  OPTIMIZER_REFINE_ROUNDS,
  OPTIMIZER_REFINE_SEEDS,
  OPTIMIZER_MAX_EXPANSIONS,
  OPTIMIZER_REFINE_BUDGET,
  OPTIMIZER_PET_OPTIONS,
  OPTIMIZER_PET_LABELS,
  OPTIMIZER_TIER1_STEPS,
  OPTIMIZER_ENGRAVING_ROLES,
  OPTIMIZER_ROLE_LABELS,
  DIRECTION_REQUIREMENT_LABELS,
  OPTIMIZER_INERT_NODES,
  getModeledStatKeys,
  isNodeImpactful,
  enumerateNodeCombos,
  keepFullBudgetCombos,
  getModeledEngravings,
  DEFAULT_CANDIDATES,
  defaultEngravingRole,
  enumerateEngravingSets,
  createTopList,
  createParetoFront,
  createChunkClock,
  BEAM_METRICS,
  selectBeam,
};
