// GENERATED by scripts/extract-core.mjs - do not edit by hand.
// Source: ../../../../legacy/app.js

function readNumber(value) {
  const number = Number(value);
  return Number.isFinite(number) ? number : 0;
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function cloneState(value) {
  return JSON.parse(JSON.stringify(value));
}

function makeId() {
  return `id-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function formatNumber(value) {
  return readNumber(value).toLocaleString("ko-KR", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function formatInteger(value) {
  return Math.round(readNumber(value)).toLocaleString("ko-KR");
}

function formatInputValue(value) {
  return Number.isFinite(Number(value)) ? String(value) : "0";
}

function percentDelta(value, base) {
  if (!Number.isFinite(value) || !Number.isFinite(base) || base === 0) return 0;
  return (value / base - 1) * 100;
}

function formatSignedPercent(value) {
  const sign = value >= 0 ? "+" : "";
  return `${sign}${formatNumber(value)}%`;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export {
  readNumber,
  clamp,
  cloneState,
  makeId,
  formatNumber,
  formatInteger,
  formatInputValue,
  percentDelta,
  formatSignedPercent,
  escapeHtml,
};
