// GENERATED by scripts/extract-core.mjs — do not edit by hand.
// Source: ../../../../app.js (damage model)

import { ARC_PASSIVE_CONSTANTS, ACCESSORY_OPTION_VALUES, EVOLUTION_TIERS, NODE_LIBRARY } from "./data.js";
import { BRACELET_GRADES, BRACELET_STAT_FIELDS, BRACELET_EFFECTS } from "./bracelets.js";
import { ENGRAVING_TIERS, ENGRAVING_LIBRARY } from "./engravings.js";
import { readNumber, clamp, cloneState, makeId } from "./util.js";

const DEFAULT_STATE = {
  base: {
    critStat: 80,
    specStat: 50,
    swiftStat: 70,
    dominationStat: 0,
    enduranceStat: 0,
    expertiseStat: 0,
    baseCritRate: 0,
    critDamageBonus: 0,
    specDamagePer100: 0,
  },
  settings: {
    pointBudget: 140,
    includeCooldown: true,
    includeAttackSpeed: false,
    backAttack: false,
    headAttack: false,
  },
  convenience: {
    petStat: "none",
    evolutionKarmaRank: 0,
    manaShare: 100,
    goddessBlessing: false,
    feast: false,
  },
  accessories: {
    necklace: { additionalDamage: "none" },
    rings: [
      { critRate: "none", critDamage: "none" },
      { critRate: "none", critDamage: "none" },
    ],
  },
  bracelet: {
    stats: { critStat: 0, specStat: 0, swiftStat: 0 },
    effects: {},
  },
  engravings: {},
  nodeLevels: {},
  baseEffects: [
    { id: makeId(), label: "카드 추가 피해", category: "damage:추가 피해", customCategory: "", amount: 0 },
    { id: makeId(), label: "각인/시너지 치적", category: "critRate", customCategory: "", amount: 0 },
    { id: makeId(), label: "추가 치명타 피해", category: "critDamage", customCategory: "", amount: 0 },
  ],
  selectedTier: "전체",
  setupName: "",
};

const MULTIPLICATIVE_DAMAGE_GROUPS = new Set(["주는 피해"]);

function getManaShareRatio(convenience) {
  return clamp(readNumber(convenience?.manaShare ?? 100), 0, 100) / 100;
}

function calculateMetrics(inputState) {
  const convenience = { ...DEFAULT_STATE.convenience, ...(inputState.convenience || {}) };
  const manaShare = getManaShareRatio(convenience);
  const accessories = normalizeAccessories(inputState.accessories);
  const bracelet = normalizeBracelet(inputState.bracelet);
  const totalStats = {
    critStat: readNumber(inputState.base.critStat),
    specStat: readNumber(inputState.base.specStat),
    swiftStat: readNumber(inputState.base.swiftStat),
    dominationStat: readNumber(inputState.base.dominationStat),
    enduranceStat: readNumber(inputState.base.enduranceStat),
    expertiseStat: readNumber(inputState.base.expertiseStat),
  };
  if (Object.hasOwn(totalStats, convenience.petStat)) {
    totalStats[convenience.petStat] += ARC_PASSIVE_CONSTANTS.petStatBonus;
  }
  const percentBonuses = {
    critRate: readNumber(inputState.base.baseCritRate),
    critDamage: 0,
    attackSpeed: 0,
    attackSpeedOnly: 0,
    moveSpeedOnly: 0,
    cooldownReduction: 0,
    cooldownIncrease: 0,
    manaCooldownReduction: 0,
    skillCooldownReduction: 0,
    critOnlyDamage: 0,
  };
  const damageGroups = {};
  const specials = {
    bluntThorn: 0,
    sonicBreakthrough: 0,
  };
  let pointsUsed = 0;

  NODE_LIBRARY.forEach(node => {
    const level = clamp(Math.round(inputState.nodeLevels?.[node.id] || 0), 0, node.maxLevel);
    pointsUsed += level * getNodeCost(node);
    node.effects.forEach(effect => {
      applyEffect(effect, level, totalStats, percentBonuses, damageGroups, specials, manaShare);
    });
  });

  (inputState.baseEffects || []).forEach(effect => {
    applyBaseEffect(effect, percentBonuses, damageGroups);
  });

  const accessoryBonuses = calculateAccessoryBonuses(accessories);
  percentBonuses.critRate += accessoryBonuses.critRate;
  percentBonuses.critDamage += accessoryBonuses.critDamage;
  addDamageGroup(damageGroups, "추가 피해", accessoryBonuses.additionalDamage);

  const karmaDamage = clamp(Math.round(readNumber(convenience.evolutionKarmaRank)), 0, 6);
  addDamageGroup(damageGroups, "진화형 피해", karmaDamage);

  const goddessNodeLevel = clamp(
    Math.round(readNumber(inputState.nodeLevels?.["e2-goddess-blessing"])),
    0,
    3,
  );
  if (convenience.goddessBlessing) {
    const goddessNodeSpeed = goddessNodeLevel * 3;
    percentBonuses.attackSpeed += Math.max(0, ARC_PASSIVE_CONSTANTS.goddessBlessingSpeed - goddessNodeSpeed);
  }
  if (convenience.feast) {
    percentBonuses.attackSpeed += ARC_PASSIVE_CONSTANTS.feastSpeed;
  }

  if (inputState.settings.backAttack) {
    percentBonuses.critRate += ARC_PASSIVE_CONSTANTS.backAttackCritRate;
    addDamageGroup(damageGroups, "주는 피해", ARC_PASSIVE_CONSTANTS.backAttackDamage);
  }
  if (inputState.settings.headAttack) {
    addDamageGroup(damageGroups, "헤드어택 피해", ARC_PASSIVE_CONSTANTS.headAttackDamage);
  }

  applyBraceletEffects(bracelet, inputState.settings, totalStats, percentBonuses, damageGroups);

  const engravingSpecials = applyEngravingEffects(
    inputState.engravings,
    percentBonuses,
    damageGroups,
    manaShare,
    inputState.settings,
  );

  return finalizeMetrics({
    settings: inputState.settings,
    specDamagePer100: readNumber(inputState.base.specDamagePer100),
    critDamageBonus: readNumber(inputState.base.critDamageBonus),
    totalStats,
    percentBonuses,
    damageGroups,
    specials,
    engravingSpecials,
    pointsUsed,
    accessoryBonuses,
  });
}

function finalizeMetrics(context) {
  const {
    settings,
    specDamagePer100,
    critDamageBonus,
    totalStats,
    percentBonuses,
    damageGroups,
    specials,
    engravingSpecials,
    pointsUsed,
    accessoryBonuses,
  } = context;

  const specDamage = (totalStats.specStat / 100) * readNumber(specDamagePer100);
  if (specDamage !== 0) {
    addDamageGroup(damageGroups, "특화 효율", specDamage);
  }

  const critRateFromStat = totalStats.critStat * ARC_PASSIVE_CONSTANTS.critRatePerCrit;
  const attackSpeedFromSwift = totalStats.swiftStat * ARC_PASSIVE_CONSTANTS.attackSpeedPerSwift;
  const cooldownFromSwift = totalStats.swiftStat * ARC_PASSIVE_CONSTANTS.cooldownPerSwift;
  const critRateRaw = Math.max(
    critRateFromStat + percentBonuses.critRate,
    engravingSpecials.critRateMinimum,
  );
  const sharedSpeedBonus = attackSpeedFromSwift + percentBonuses.attackSpeed;
  const attackSpeed = sharedSpeedBonus + percentBonuses.attackSpeedOnly;
  const moveSpeedBonus = sharedSpeedBonus + percentBonuses.moveSpeedOnly;
  const attackSpeedRaw = 100 + attackSpeed;
  const moveSpeedRaw = 100 + moveSpeedBonus;
  const attackSpeedExcess = Math.max(0, attackSpeedRaw - 140);
  const moveSpeedExcess = Math.max(0, moveSpeedRaw - 140);
  const appliedAttackSpeedBonus = clamp(attackSpeed, -99, 40);
  const attackMoveSpeed = 100 + appliedAttackSpeedBonus;
  const moveSpeed = 100 + clamp(moveSpeedBonus, -99, 40);
  const raidCaptainDamage = clamp(moveSpeedBonus, 0, 40) * engravingSpecials.raidCaptainRate / 100;
  addDamageGroup(damageGroups, "주는 피해", raidCaptainDamage);
  const globalCooldownReduction = cooldownFromSwift + percentBonuses.cooldownReduction;
  const cooldownGroups = {
    global: globalCooldownReduction,
    mana: globalCooldownReduction + percentBonuses.manaCooldownReduction,
    skill: globalCooldownReduction + percentBonuses.skillCooldownReduction,
  };
  const cooldownReduction = Math.max(cooldownGroups.global, cooldownGroups.mana, cooldownGroups.skill);
  const cooldownGroupLabel = getCooldownGroupLabel(cooldownGroups, cooldownReduction);
  const bluntThornBonus = calculateBluntThornBonus(specials.bluntThorn, critRateRaw);
  const sonicBreakdown = calculateSonicBreakthroughBonus(
    specials.sonicBreakthrough,
    attackSpeed,
    moveSpeedBonus,
  );
  const sonicBonus = sonicBreakdown.damage;
  if (bluntThornBonus.damage > 0) {
    addDamageGroup(damageGroups, "진화형 피해", bluntThornBonus.damage);
  }
  if (sonicBonus > 0) {
    addDamageGroup(damageGroups, "진화형 피해", sonicBonus);
  }

  const critCap = specials.bluntThorn > 0 ? 80 : 100;
  const critRateCapped = clamp(critRateRaw, 0, critCap);
  const critDamage = Math.max(
    100,
    ARC_PASSIVE_CONSTANTS.baseCritDamage + readNumber(critDamageBonus) + percentBonuses.critDamage,
  );

  const critChance = critRateCapped / 100;
  const critOnlyMultiplier = 1 + percentBonuses.critOnlyDamage / 100;
  const critFactor = (1 - critChance) + critChance * (critDamage / 100) * critOnlyMultiplier;
  const damageMultiplier = Object.values(damageGroups).reduce((acc, value) => acc * (1 + value / 100), 1);
  const cooldownIncrease = Math.max(0, percentBonuses.cooldownIncrease);
  const cooldownFactor = settings.includeCooldown
    ? 1 / ((1 - clamp(cooldownReduction, 0, 80) / 100) * (1 + cooldownIncrease / 100))
    : 1;
  const attackSpeedFactor = settings.includeAttackSpeed ? attackMoveSpeed / 100 : 1;
  const damageIndex = 100 * critFactor * damageMultiplier;
  const dpsIndex = damageIndex * cooldownFactor * attackSpeedFactor;

  return {
    totalStats,
    percentBonuses,
    damageGroups,
    specials,
    engravingSpecials,
    bluntThornBonus,
    sonicBonus,
    sonicBreakdown,
    pointsUsed,
    critRateFromStat,
    critRateRaw,
    critRateCapped,
    critDamage,
    attackSpeed,
    attackSpeedRaw,
    attackSpeedExcess,
    attackMoveSpeed,
    moveSpeedBonus,
    moveSpeedRaw,
    moveSpeedExcess,
    moveSpeed,
    raidCaptainDamage,
    accessoryBonuses,
    cooldownGroups,
    cooldownGroupLabel,
    cooldownReduction,
    cooldownIncrease,
    critOnlyDamage: percentBonuses.critOnlyDamage,
    critFactor,
    damageMultiplier,
    cooldownFactor,
    attackSpeedFactor,
    damageIndex,
    dpsIndex,
  };
}

function applyEffect(effect, level, totalStats, percentBonuses, damageGroups, specials, manaShare) {
  if (effect.kind === "note") return;
  if (effect.kind === "special") {
    if (level > 0) specials[effect.key] = Math.max(specials[effect.key] || 0, level);
    return;
  }

  const amount = readNumber(effect.amount) * level * (effect.manaOnly ? manaShare : 1);
  if (amount === 0) return;

  if (effect.kind === "stat") {
    totalStats[effect.key] = readNumber(totalStats[effect.key]) + amount;
    return;
  }

  if (effect.kind === "damage") {
    addDamageGroup(damageGroups, effect.key, amount);
    return;
  }

  if (effect.kind === "critOnlyDamage") {
    percentBonuses.critOnlyDamage = readNumber(percentBonuses.critOnlyDamage) + amount;
    return;
  }

  percentBonuses[effect.key] = readNumber(percentBonuses[effect.key]) + amount;
}

function applyBaseEffect(effect, percentBonuses, damageGroups) {
  const amount = readNumber(effect.amount);
  if (amount === 0) return;

  if (effect.category === "customDamage") {
    const label = (effect.customCategory || effect.label || "기타 피해").trim();
    addDamageGroup(damageGroups, label, amount);
    return;
  }

  if (effect.category.startsWith("damage:")) {
    const label = effect.category.slice("damage:".length);
    addDamageGroup(damageGroups, label, amount);
    return;
  }

  percentBonuses[effect.category] = readNumber(percentBonuses[effect.category]) + amount;
}

function applyEngravingEffects(engravingState, percentBonuses, damageGroups, manaShare, settings) {
  const engravingSpecials = {
    critRateMinimum: 0,
    raidCaptainRate: 0,
  };

  ENGRAVING_LIBRARY.forEach(engravingItem => {
    const tierIndex = getEngravingTierIndex(engravingState?.[engravingItem.id]);
    if (tierIndex < 0) return;
    applyEngravingTier(engravingItem, tierIndex, percentBonuses, damageGroups, engravingSpecials, manaShare, settings);
  });

  return engravingSpecials;
}

function applyEngravingTier(engravingItem, tierIndex, percentBonuses, damageGroups, engravingSpecials, manaShare, settings) {
  // Directional engravings follow the same 백어택/헤드어택 gating as bracelets,
  // so head-attack and back-attack effects can never stack on one hit.
  if (!isDirectionalConditionActive(engravingItem.condition, settings)) return;

  engravingItem.effects.forEach(effect => {
    const amount = readNumber(effect.amounts?.[tierIndex]) * (effect.manaOnly ? manaShare : 1);
    if (effect.kind === "damage") {
      addDamageGroup(damageGroups, effect.key, amount);
      return;
    }
    if (effect.kind === "percent") {
      percentBonuses[effect.key] = readNumber(percentBonuses[effect.key]) + amount;
      return;
    }
    if (effect.kind === "special") {
      engravingSpecials[effect.key] = Math.max(readNumber(engravingSpecials[effect.key]), amount);
    }
  });
}

function getEngravingTierIndex(value) {
  return ENGRAVING_TIERS.findIndex(tier => tier.value === value);
}

function normalizeBracelet(bracelet) {
  const stats = BRACELET_STAT_FIELDS.reduce((result, item) => {
    result[item.key] = clamp(Math.round(readNumber(bracelet?.stats?.[item.key])), 0, 120);
    return result;
  }, {});
  const effects = {};

  BRACELET_EFFECTS.forEach(item => {
    const grade = bracelet?.effects?.[item.id];
    if (getBraceletGradeIndex(grade) >= 0) effects[item.id] = grade;
  });

  return { stats, effects };
}

function applyBraceletEffects(bracelet, settings, totalStats, percentBonuses, damageGroups) {
  BRACELET_STAT_FIELDS.forEach(item => {
    totalStats[item.key] = readNumber(totalStats[item.key]) + readNumber(bracelet.stats[item.key]);
  });

  BRACELET_EFFECTS.forEach(item => {
    const gradeIndex = getBraceletGradeIndex(bracelet.effects[item.id]);
    if (gradeIndex < 0 || !isDirectionalConditionActive(item.condition, settings)) return;

    item.effects.forEach(effect => {
      const amount = readNumber(effect.amounts?.[gradeIndex]);
      if (effect.kind === "damage") {
        addDamageGroup(damageGroups, effect.key, amount);
        return;
      }
      if (effect.kind === "percent") {
        percentBonuses[effect.key] = readNumber(percentBonuses[effect.key]) + amount;
      }
    });
  });
}

function getBraceletGradeIndex(value) {
  return BRACELET_GRADES.findIndex(grade => grade.value === value);
}

function isDirectionalConditionActive(condition, settings) {
  if (!condition) return true;
  if (condition === "backAttack") return Boolean(settings?.backAttack);
  if (condition === "headAttack") return Boolean(settings?.headAttack);
  if (condition === "nonDirectional") return !settings?.backAttack && !settings?.headAttack;
  return false;
}

function normalizeAccessories(accessories) {
  const nextRings = Array.isArray(accessories?.rings) ? accessories.rings : [];
  return {
    necklace: {
      ...DEFAULT_STATE.accessories.necklace,
      ...(accessories?.necklace || {}),
    },
    rings: DEFAULT_STATE.accessories.rings.map((ring, index) => ({
      ...ring,
      ...(nextRings[index] || {}),
    })),
  };
}

function calculateAccessoryBonuses(accessories) {
  const result = {
    additionalDamage: getAccessoryOptionValue("necklace", "additionalDamage", accessories.necklace.additionalDamage),
    critRate: 0,
    critDamage: 0,
  };

  accessories.rings.forEach(ring => {
    result.critRate += getAccessoryOptionValue("ring", "critRate", ring.critRate);
    result.critDamage += getAccessoryOptionValue("ring", "critDamage", ring.critDamage);
  });
  return result;
}

function getAccessoryOptionValue(part, field, grade) {
  return readNumber(ACCESSORY_OPTION_VALUES[part]?.[field]?.[grade]);
}

function addDamageGroup(damageGroups, key, amount) {
  const value = readNumber(amount);
  if (value === 0) return;

  if (MULTIPLICATIVE_DAMAGE_GROUPS.has(key)) {
    const currentMultiplier = 1 + readNumber(damageGroups[key]) / 100;
    const nextMultiplier = currentMultiplier * (1 + value / 100);
    damageGroups[key] = (nextMultiplier - 1) * 100;
    return;
  }

  damageGroups[key] = readNumber(damageGroups[key]) + value;
}

function calculateBluntThornBonus(level, critRateRaw) {
  if (level <= 0) return { damage: 0, convertedCrit: 0 };
  const excessCritRate = Math.max(0, readNumber(critRateRaw) - 80);
  const conversionRate = level >= 2 ? 1.5 : 1.25;
  const conversionLimit = level >= 2 ? 60 : 45;
  return {
    damage: Math.min(excessCritRate * conversionRate, conversionLimit),
    convertedCrit: Math.min(excessCritRate, conversionLimit / conversionRate),
  };
}

function calculateSonicBreakthroughBonus(level, attackSpeedBonus, moveSpeedBonus) {
  if (level <= 0) {
    return { damage: 0, baseDamage: 0, capBonus: 0, excessDamage: 0 };
  }

  const maxDamage = level >= 2 ? 24 : 12;
  const baseRate = level >= 2 ? 0.1 : 0.05;
  const fixedCapBonus = level >= 2 ? 8 : 4;
  const excessRate = level >= 2 ? 0.3 : 0.15;
  const appliedAttackBonus = clamp(readNumber(attackSpeedBonus), 0, 40);
  const appliedMoveBonus = clamp(readNumber(moveSpeedBonus), 0, 40);
  const attackExcess = Math.max(0, readNumber(attackSpeedBonus) - 40);
  const moveExcess = Math.max(0, readNumber(moveSpeedBonus) - 40);
  const bothOverCap = attackExcess > 0 && moveExcess > 0;
  const baseDamage = (appliedAttackBonus + appliedMoveBonus) * baseRate;
  const capBonus = bothOverCap ? fixedCapBonus : 0;
  const rawExcessDamage = bothOverCap ? (attackExcess + moveExcess) * excessRate : 0;
  const excessDamage = Math.min(rawExcessDamage, Math.max(0, maxDamage - baseDamage - capBonus));

  return {
    damage: baseDamage + capBonus + excessDamage,
    baseDamage,
    capBonus,
    excessDamage,
  };
}

function getCooldownGroupLabel(groups, selectedValue) {
  const epsilon = 0.0001;
  const labels = [];
  if (groups.mana > groups.global + epsilon && Math.abs(groups.mana - selectedValue) < epsilon) labels.push("끝마/무마");
  if (groups.skill > groups.global + epsilon && Math.abs(groups.skill - selectedValue) < epsilon) labels.push("최훈/타지");
  if (labels.length === 0) labels.push("공통");
  return labels.join(", ");
}

function getNodeCost(node) {
  return node.cost || EVOLUTION_TIERS[node.tier]?.cost || 0;
}

function normalizeNodeLevels(nodeLevels) {
  return NODE_LIBRARY.reduce((levels, node) => {
    levels[node.id] = clamp(Math.round(readNumber(nodeLevels?.[node.id])), 0, node.maxLevel);
    return levels;
  }, {});
}

function emptyNodeLevels() {
  return NODE_LIBRARY.reduce((levels, node) => {
    levels[node.id] = 0;
    return levels;
  }, {});
}

function mergeState(base, next) {
  const nextBase = { ...(next.base || {}) };
  if (typeof nextBase.critDamageBonus !== "number" && typeof nextBase.baseCritDamage === "number") {
    nextBase.critDamageBonus = readNumber(nextBase.baseCritDamage) - ARC_PASSIVE_CONSTANTS.baseCritDamage;
  }
  delete nextBase.baseCritDamage;

  const accessories = normalizeAccessories(next.accessories);
  const bracelet = normalizeBracelet(next.bracelet);

  return {
    base: { ...base.base, ...nextBase },
    settings: { ...base.settings, ...(next.settings || {}) },
    convenience: { ...base.convenience, ...(next.convenience || {}) },
    accessories,
    bracelet,
    engravings: { ...(next.engravings || {}) },
    nodeLevels: { ...(next.nodeLevels || {}) },
    baseEffects: normalizeBaseEffects(next.baseEffects, base.baseEffects),
    selectedTier: next.selectedTier || base.selectedTier,
    setupName: next.setupName || "",
  };
}

function normalizeBaseEffects(effects, fallbackEffects) {
  const source = Array.isArray(effects) ? effects : cloneState(fallbackEffects);

  return source.flatMap(effect => {
    if (effect.category !== "attackSpeed") return [effect];

    const id = effect.id || makeId();
    const label = String(effect.label || "공격/이동속도").trim();
    const genericLabel = /공격\s*\/?\s*이동속도|공이속/.test(label);
    return [
      {
        ...effect,
        id,
        label: genericLabel ? "공격속도" : `${label} · 공속`,
        category: "attackSpeedOnly",
      },
      {
        ...effect,
        id: `${id}-move`,
        label: genericLabel ? "이동속도" : `${label} · 이속`,
        category: "moveSpeedOnly",
      },
    ];
  });
}

export {
  DEFAULT_STATE,
  MULTIPLICATIVE_DAMAGE_GROUPS,
  getManaShareRatio,
  calculateMetrics,
  finalizeMetrics,
  applyEffect,
  applyBaseEffect,
  applyEngravingEffects,
  applyEngravingTier,
  getEngravingTierIndex,
  normalizeBracelet,
  applyBraceletEffects,
  getBraceletGradeIndex,
  isDirectionalConditionActive,
  normalizeAccessories,
  calculateAccessoryBonuses,
  getAccessoryOptionValue,
  addDamageGroup,
  calculateBluntThornBonus,
  calculateSonicBreakthroughBonus,
  getCooldownGroupLabel,
  getNodeCost,
  normalizeNodeLevels,
  emptyNodeLevels,
  mergeState,
  normalizeBaseEffects,
};
