// Lifts the verified calculation/search logic out of the legacy browser scripts
// into ES modules, copying declarations verbatim so the math cannot drift.
// Re-runnable: regenerates src/lib/core/*.js from ../legacy/*.js.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const LEGACY = resolve(HERE, "../legacy");
const OUT = resolve(HERE, "../src/lib/core");

const read = name => readFileSync(resolve(LEGACY, name), "utf8");

// Slice a top-level `function NAME(...) {...}` or `const NAME = ...;` verbatim.
function sliceDeclaration(source, name) {
  const patterns = [
    new RegExp(`^function ${name}\\s*\\(`, "m"),
    new RegExp(`^const ${name}\\s*=`, "m"),
  ];

  for (const pattern of patterns) {
    const match = pattern.exec(source);
    if (!match) continue;
    const start = match.index;

    if (match[0].startsWith("function")) {
      let i = source.indexOf("{", start);
      let depth = 0;
      for (; i < source.length; i += 1) {
        if (source[i] === "{") depth += 1;
        else if (source[i] === "}") {
          depth -= 1;
          if (depth === 0) return source.slice(start, i + 1);
        }
      }
      throw new Error(`unterminated function ${name}`);
    }

    // const: walk to the semicolon that closes the initialiser at depth 0.
    let depth = 0;
    for (let i = start; i < source.length; i += 1) {
      const ch = source[i];
      if ("{[(".includes(ch)) depth += 1;
      else if ("}])".includes(ch)) depth -= 1;
      else if (ch === ";" && depth === 0) return source.slice(start, i + 1);
    }
    throw new Error(`unterminated const ${name}`);
  }

  throw new Error(`declaration not found: ${name}`);
}

function buildModule({ header, imports = [], source, names, exportNames }) {
  const bodies = names.map(name => sliceDeclaration(source, name));
  const exported = exportNames ?? names;
  return [
    "// GENERATED by scripts/extract-core.mjs - do not edit by hand.",
    `// ${header}`,
    "",
    ...imports,
    imports.length > 0 ? "" : null,
    bodies.join("\n\n"),
    "",
    `export {\n${exported.map(n => `  ${n},`).join("\n")}\n};`,
    "",
  ].filter(line => line !== null).join("\n");
}

mkdirSync(OUT, { recursive: true });

// --- data tables: copied whole, exports appended -----------------------------
const dataExports = [
  "ARC_PASSIVE_CONSTANTS", "ACCESSORY_OPTION_VALUES", "REFERENCE_META", "REFERENCE_RULES",
  "REFERENCE_HIGHLIGHTS", "REFERENCE_WARNINGS", "EVOLUTION_TIERS", "EFFECT_CATEGORIES",
  "NODE_LIBRARY", "NODE_CONTEXT",
];
writeFileSync(
  resolve(OUT, "data.js"),
  `// GENERATED by scripts/extract-core.mjs - do not edit by hand.\n// Source: ../../../../legacy/data.js\n\n${read("data.js")}\nexport {\n${dataExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

const braceletExports = ["BRACELET_GRADES", "BRACELET_STAT_FIELDS", "BRACELET_EFFECTS", "BRACELET_UNSUPPORTED_EFFECTS"];
writeFileSync(
  resolve(OUT, "bracelets.js"),
  `// GENERATED by scripts/extract-core.mjs - do not edit by hand.\n// Source: ../../../../legacy/bracelets.js\n\n${read("bracelets.js")}\nexport {\n${braceletExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

// 깨달음·도약 — 손으로 붙인 효과 표. 구조는 arkpassive-tree.js가 들고 있고
// (scripts/build-arkpassive.mjs가 인벤 원본에서 만든다) 여기서는 읽기만 한다.
const awakeningExports = [
  "AWAKENING_GROUPS", "getAwakeningNodes",
  "hasAwakeningTree", "isAwakeningModeled", "awakeningBranchNote", "awakeningGroupInfo",
  "awakeningBonuses", "checkAwakening", "awakeningHeadroom", "awakeningDependents", "awakeningFix",
];
writeFileSync(
  resolve(OUT, "awakening.js"),
  `// GENERATED by scripts/extract-core.mjs - do not edit by hand.\n// Source: ../../../../legacy/awakening.js\n\nimport { readNumber, clamp } from "./util.js";\nimport { ARKPASSIVE_TREE } from "../data/arkpassive-tree.js";
import { AWAKENING_EFFECTS } from "../data/awakening-effects/index.js";
import AWAKENING_SCOPE from "../data/awakening-scope.json" with { type: "json" };\n\n${read("awakening.js")}\nexport {\n${awakeningExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

// 파티 시너지 — 표와 합산 규칙.
const synergyExports = [
  "SYNERGY_TYPES", "SYNERGY_TYPE_ORDER", "SYNERGY_JOBS", "SYNERGY_SLOTS",
  "SYNERGY_UPTIME_FULL", "SYNERGY_BASE_KEY", "SYNERGY_OWN_ID",
  "GENERIC_SYNERGY_JOBS", "isGenericSynergyJob", "genericSynergyName",
  "getSynergyJob", "synergyAmount", "findSynergyChoice", "synergyRowParts", "defaultSynergyNodes",
  "jobSelfBuffs", "jobBranches", "takenBranch", "jobStat", "jobDirection", "JOB_BUFFS",
  "ownSynergyRow", "normalizeUptime", "normalizeUptimeMap", "synergyRowUptime",
  "defaultChoiceUptime", "synergyChoiceNote", "normalizeSynergyRows", "synergyBonuses",
];
writeFileSync(
  resolve(OUT, "synergy.js"),
  `// GENERATED by scripts/extract-core.mjs - do not edit by hand.\n// Source: ../../../../legacy/synergy.js\n\nimport { readNumber } from "./util.js";\nimport JOB_BUFFS from "../data/job-buffs.json" with { type: "json" };\n\n${read("synergy.js")}\nexport {\n${synergyExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

const coreExports = [
  "CHAOS_CORE_POINTS", "CHAOS_CORE_SLOTS", "CHAOS_CORE_STAGES", "CHAOS_CORES",
  "ORDER_CORE_SLOTS", "emptyOrderCores",
  "ARK_GRID_GEM_EFFECTS", "arkGridGemDamage", "GEM_MAX_LEVEL", "STANDALONE_SOURCES",
  "WEAPON_QUALITY_MAX", "weaponQualityDamage",
];
// 젬 계산이 들어오면서 clamp/readNumber를 쓴다 — 데이터 표지만 import가 붙는다.
writeFileSync(
  resolve(OUT, "cores.js"),
  `// GENERATED by scripts/extract-core.mjs - do not edit by hand.\n// Source: ../../../../legacy/cores.js\n\nimport { readNumber, clamp } from "./util.js";\n\n${read("cores.js")}\nexport {\n${coreExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

const engravingExports = ["ENGRAVING_TIERS", "LEGACY_ENGRAVING_TIERS", "engravingAmount", "ENGRAVING_STONE", "engravingStoneAmount", "ENGRAVING_LIBRARY"];
writeFileSync(
  resolve(OUT, "engravings.js"),
  `// GENERATED by scripts/extract-core.mjs - do not edit by hand.\n// Source: ../../../../legacy/engravings.js\n\nimport { readNumber } from "./util.js";\n\n${read("engravings.js")}\nexport {\n${engravingExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

// --- pure helpers -----------------------------------------------------------
const app = read("app.js");

writeFileSync(resolve(OUT, "util.js"), buildModule({
  header: "Source: ../../../../legacy/app.js",
  source: app,
  names: [
    "readNumber", "clamp", "cloneState", "makeId",
    "formatNumber", "formatInteger", "formatInputValue",
    "percentDelta", "formatSignedPercent", "escapeHtml",
  ],
}));

// --- damage model -----------------------------------------------------------
writeFileSync(resolve(OUT, "metrics.js"), buildModule({
  header: "Source: ../../../../legacy/app.js (damage model)",
  imports: [
    'import { ARC_PASSIVE_CONSTANTS, ACCESSORY_OPTION_VALUES, EVOLUTION_TIERS, NODE_LIBRARY } from "./data.js";',
    'import { BRACELET_GRADES, BRACELET_STAT_FIELDS, BRACELET_EFFECTS } from "./bracelets.js";',
    'import {',
    '  ENGRAVING_TIERS, ENGRAVING_LIBRARY, engravingAmount, engravingStoneAmount, LEGACY_ENGRAVING_TIERS,',
    '} from "./engravings.js";',
    'import {',
    '  CHAOS_CORE_POINTS, CHAOS_CORE_SLOTS, CHAOS_CORE_STAGES, CHAOS_CORES, emptyOrderCores,',
    '  ARK_GRID_GEM_EFFECTS, arkGridGemDamage, GEM_MAX_LEVEL, STANDALONE_SOURCES,',
    '  WEAPON_QUALITY_MAX, weaponQualityDamage,',
    '} from "./cores.js";',
    'import { awakeningBonuses } from "./awakening.js";',
    'import {',
    '  SYNERGY_SLOTS, getSynergyJob, normalizeSynergyRows, normalizeUptimeMap, synergyBonuses,',
    '} from "./synergy.js";',
    'import { readNumber, clamp, cloneState, makeId } from "./util.js";',
  ],
  source: app,
  names: [
    "DEFAULT_STATE", "MULTIPLICATIVE_DAMAGE_GROUPS", "SQRT_DAMAGE_GROUPS", "ATTACK_CHAIN_GROUPS", "damageGroupFactor",
    "normalizeSynergy", "legacySynergyRows", "STAGGER_DAMAGE_GROUPS", "getStaggerShare",
    "normalizeArkGrid", "applyCoreEffect", "applyArkGridEffects", "applyCollectionEffects", "applyWeaponEffects",
    "DAMAGE_MIX_KEYS", "DAMAGE_MIX_LABELS", "normalizeDamageMix",
    "SPEC_BUNDLE_KINDS", "normalizeSpecBundles", "specBundleValue", "specBundleRowFactor", "specBundleVariables", "specBundleBlend",
    "getManaShareRatio", "getManaCooldownShareRatio", "blendCooldownRemain",
    "calculateMetrics", "finalizeMetrics",
    "addCritOnlyDamage", "applyEffect", "applyBaseEffect", "effectUptimeRate",
    "FORMULA_VARIABLES", "getFormulaStage", "evaluateFormula", "buildFormulaVariables", "applyFormulaEffects",
    "applyEngravingEffects", "applyEngravingTier", "getEngravingTierIndex",
    "normalizeBracelet", "applyBraceletEffects", "getBraceletGradeIndex", "isDirectionalConditionActive",
    "normalizeAccessories", "calculateAccessoryBonuses", "getAccessoryOptionValue",
    "normalizeAttack", "assembleAttack", "SUPPORT_BUFF_BY_LEVEL", "supportAttackPower", "baseAttackPower", "emptyFlatBonuses", "applyFlatAttackBonuses", "addFlatBonus",
    "FOODS", "FOOD_BY_ID", "getFood", "applyFoodEffects", "RANCH_GRADES", "ranchAmount",
    "PASSION_DANCE_GRADES", "passionDanceAmount", "AVATAR_SLOTS", "AVATAR_GRADES", "avatarAmount", "avatarTotal", "derivedMainTotal", "ranchResidual", "outsideMainStat", "autoRanchAmount", "resolveRanchMainStat", "resolveRanchDamage",
    "applyAwakeningEffects", "applySynergyEffects",
    "addDamageGroup", "calculateBluntThornBonus", "calculateSonicBreakthroughBonus",
    "COOLDOWN_GROUP_KEYS", "COOLDOWN_GROUP_LABELS", "JEWEL_MAX_LEVEL", "jewelCooldown",
    "getCooldownGroupLabel", "getNodeCost",
    "normalizeNodeLevels", "emptyNodeLevels", "mergeState", "normalizeBaseEffects",
  ],
}));

// --- combination search -----------------------------------------------------
const optimizer = read("optimizer.js");

writeFileSync(resolve(OUT, "search.js"), buildModule({
  header: "Source: ../../../../legacy/optimizer.js (search engine, UI stripped)",
  imports: [
    'import { EVOLUTION_TIERS, NODE_LIBRARY, ARC_PASSIVE_CONSTANTS } from "./data.js";',
    'import { ENGRAVING_TIERS, ENGRAVING_LIBRARY } from "./engravings.js";',
    'import { readNumber, clamp } from "./util.js";',
    'import {',
    '  DEFAULT_STATE, finalizeMetrics, applyBaseEffect, applyBraceletEffects, applyEngravingTier,',
    '  calculateAccessoryBonuses, normalizeAccessories, normalizeBracelet, addDamageGroup,',
    '  getEngravingTierIndex, getManaShareRatio, getNodeCost, emptyNodeLevels,',
    '  FOODS, assembleAttack,',
    '} from "./metrics.js";',
  ],
  source: optimizer,
  names: [
    "OPTIMIZER_EXHAUSTIVE_LIMIT", "OPTIMIZER_CHUNK_MS", "OPTIMIZER_CLOCK_INTERVAL",
    "OPTIMIZER_REFINE_ROUNDS", "OPTIMIZER_REFINE_SEEDS",
    "OPTIMIZER_MAX_EXPANSIONS", "OPTIMIZER_REFINE_BUDGET",
    "OPTIMIZER_PET_OPTIONS", "OPTIMIZER_PET_LABELS", "OPTIMIZER_TIER1_STEPS",
    "OPTIMIZER_ENGRAVING_ROLES", "OPTIMIZER_ROLE_LABELS", "DIRECTION_REQUIREMENT_LABELS",
    "OPTIMIZER_INERT_NODES", "getModeledStatKeys", "isNodeImpactful", "enumerateNodeCombos", "keepFullBudgetCombos",
    // toEngravingEntry is intentionally not lifted: it reads UI options, so the
    // runner re-implements it with the options passed in explicitly.
    "getModeledEngravings", "DEFAULT_CANDIDATES", "defaultEngravingRole", "enumerateEngravingSets",
    "createTopList", "createParetoFront",
    "createChunkClock", "BEAM_METRICS", "selectBeam",
  ],
}));

console.log("core modules written to src/lib/core/");
