// Lifts the verified calculation/search logic out of the legacy browser scripts
// into ES modules, copying declarations verbatim so the math cannot drift.
// Re-runnable: regenerates src/lib/core/*.js from ../legacy/*.js.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const LEGACY = resolve(HERE, "../legacy");
const OUT = resolve(HERE, "../src/lib/core");

const read = name => readFileSync(resolve(LEGACY, name), "utf8");

// Slice a top-level `function NAME(...) {...}` or `const NAME = ...;` verbatim.
function sliceDeclaration(source, name) {
  const patterns = [
    new RegExp(`^function ${name}\\s*\\(`, "m"),
    new RegExp(`^const ${name}\\s*=`, "m"),
  ];

  for (const pattern of patterns) {
    const match = pattern.exec(source);
    if (!match) continue;
    const start = match.index;

    if (match[0].startsWith("function")) {
      let i = source.indexOf("{", start);
      let depth = 0;
      for (; i < source.length; i += 1) {
        if (source[i] === "{") depth += 1;
        else if (source[i] === "}") {
          depth -= 1;
          if (depth === 0) return source.slice(start, i + 1);
        }
      }
      throw new Error(`unterminated function ${name}`);
    }

    // const: walk to the semicolon that closes the initialiser at depth 0.
    let depth = 0;
    for (let i = start; i < source.length; i += 1) {
      const ch = source[i];
      if ("{[(".includes(ch)) depth += 1;
      else if ("}])".includes(ch)) depth -= 1;
      else if (ch === ";" && depth === 0) return source.slice(start, i + 1);
    }
    throw new Error(`unterminated const ${name}`);
  }

  throw new Error(`declaration not found: ${name}`);
}

function buildModule({ header, imports = [], source, names, exportNames }) {
  const bodies = names.map(name => sliceDeclaration(source, name));
  const exported = exportNames ?? names;
  return [
    "// GENERATED by scripts/extract-core.mjs — do not edit by hand.",
    `// ${header}`,
    "",
    ...imports,
    imports.length > 0 ? "" : null,
    bodies.join("\n\n"),
    "",
    `export {\n${exported.map(n => `  ${n},`).join("\n")}\n};`,
    "",
  ].filter(line => line !== null).join("\n");
}

mkdirSync(OUT, { recursive: true });

// --- data tables: copied whole, exports appended -----------------------------
const dataExports = [
  "ARC_PASSIVE_CONSTANTS", "ACCESSORY_OPTION_VALUES", "REFERENCE_META", "REFERENCE_RULES",
  "REFERENCE_HIGHLIGHTS", "REFERENCE_WARNINGS", "EVOLUTION_TIERS", "EFFECT_CATEGORIES",
  "NODE_LIBRARY", "NODE_CONTEXT",
];
writeFileSync(
  resolve(OUT, "data.js"),
  `// GENERATED by scripts/extract-core.mjs — do not edit by hand.\n// Source: ../../../../legacy/data.js\n\n${read("data.js")}\nexport {\n${dataExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

const braceletExports = ["BRACELET_GRADES", "BRACELET_STAT_FIELDS", "BRACELET_EFFECTS", "BRACELET_UNSUPPORTED_EFFECTS"];
writeFileSync(
  resolve(OUT, "bracelets.js"),
  `// GENERATED by scripts/extract-core.mjs — do not edit by hand.\n// Source: ../../../../legacy/bracelets.js\n\n${read("bracelets.js")}\nexport {\n${braceletExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

const engravingExports = ["ENGRAVING_TIERS", "ENGRAVING_LIBRARY", "NON_RAID_ENGRAVINGS"];
writeFileSync(
  resolve(OUT, "engravings.js"),
  `// GENERATED by scripts/extract-core.mjs — do not edit by hand.\n// Source: ../../../../legacy/engravings.js\n\n${read("engravings.js")}\nexport {\n${engravingExports.map(n => `  ${n},`).join("\n")}\n};\n`,
);

// --- pure helpers -----------------------------------------------------------
const app = read("app.js");

writeFileSync(resolve(OUT, "util.js"), buildModule({
  header: "Source: ../../../../legacy/app.js",
  source: app,
  names: [
    "readNumber", "clamp", "cloneState", "makeId",
    "formatNumber", "formatInteger", "formatInputValue",
    "percentDelta", "formatSignedPercent", "escapeHtml",
  ],
}));

// --- damage model -----------------------------------------------------------
writeFileSync(resolve(OUT, "metrics.js"), buildModule({
  header: "Source: ../../../../legacy/app.js (damage model)",
  imports: [
    'import { ARC_PASSIVE_CONSTANTS, ACCESSORY_OPTION_VALUES, EVOLUTION_TIERS, NODE_LIBRARY } from "./data.js";',
    'import { BRACELET_GRADES, BRACELET_STAT_FIELDS, BRACELET_EFFECTS } from "./bracelets.js";',
    'import { ENGRAVING_TIERS, ENGRAVING_LIBRARY } from "./engravings.js";',
    'import { readNumber, clamp, cloneState, makeId } from "./util.js";',
  ],
  source: app,
  names: [
    "DEFAULT_STATE", "MULTIPLICATIVE_DAMAGE_GROUPS",
    "getManaShareRatio", "calculateMetrics", "finalizeMetrics",
    "applyEffect", "applyBaseEffect",
    "applyEngravingEffects", "applyEngravingTier", "getEngravingTierIndex",
    "normalizeBracelet", "applyBraceletEffects", "getBraceletGradeIndex", "isDirectionalConditionActive",
    "normalizeAccessories", "calculateAccessoryBonuses", "getAccessoryOptionValue",
    "addDamageGroup", "calculateBluntThornBonus", "calculateSonicBreakthroughBonus",
    "getCooldownGroupLabel", "getNodeCost",
    "normalizeNodeLevels", "emptyNodeLevels", "mergeState", "normalizeBaseEffects",
  ],
}));

// --- combination search -----------------------------------------------------
const optimizer = read("optimizer.js");

writeFileSync(resolve(OUT, "search.js"), buildModule({
  header: "Source: ../../../../legacy/optimizer.js (search engine, UI stripped)",
  imports: [
    'import { EVOLUTION_TIERS, NODE_LIBRARY, ARC_PASSIVE_CONSTANTS } from "./data.js";',
    'import { ENGRAVING_TIERS, ENGRAVING_LIBRARY, NON_RAID_ENGRAVINGS } from "./engravings.js";',
    'import { readNumber, clamp } from "./util.js";',
    'import {',
    '  DEFAULT_STATE, finalizeMetrics, applyBaseEffect, applyBraceletEffects, applyEngravingTier,',
    '  calculateAccessoryBonuses, normalizeAccessories, normalizeBracelet, addDamageGroup,',
    '  getEngravingTierIndex, getManaShareRatio, getNodeCost, emptyNodeLevels,',
    '} from "./metrics.js";',
  ],
  source: optimizer,
  names: [
    "OPTIMIZER_EXHAUSTIVE_LIMIT", "OPTIMIZER_CHUNK_MS", "OPTIMIZER_CLOCK_INTERVAL",
    "OPTIMIZER_REFINE_ROUNDS", "OPTIMIZER_REFINE_SEEDS",
    "OPTIMIZER_MAX_EXPANSIONS", "OPTIMIZER_REFINE_BUDGET",
    "OPTIMIZER_PET_OPTIONS", "OPTIMIZER_PET_LABELS", "OPTIMIZER_TIER1_STEPS",
    "OPTIMIZER_ENGRAVING_ROLES", "OPTIMIZER_ROLE_LABELS", "DIRECTION_REQUIREMENT_LABELS",
    "getModeledStatKeys", "isNodeImpactful", "enumerateNodeCombos", "keepFullBudgetCombos",
    // toEngravingEntry is intentionally not lifted: it reads UI options, so the
    // runner re-implements it with the options passed in explicitly.
    "getModeledEngravings", "defaultEngravingRole", "enumerateEngravingSets",
    "createTopList", "createParetoFront", "annotateParetoKnees",
    "createChunkClock", "selectBeam",
  ],
}));

console.log("core modules written to src/lib/core/");
